<Project Sdk="MSTest.Sdk/4.0.1">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TestingExtensionsProfile>None</TestingExtensionsProfile>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\src\base\Titanis.IO\Titanis.IO.csproj" />
	</ItemGroup>

</Project>
