<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\base\Titanis.Core\Titanis.Core.csproj" />
    <ProjectReference Include="..\..\..\base\Titanis.IO\Titanis.IO.csproj" />
    <ProjectReference Include="..\..\..\base\Titanis.Winterop.Registry\Titanis.Winterop.Registry.csproj" />
    <ProjectReference Include="..\..\Titanis.DceRpc.Core\Titanis.DceRpc.Core.csproj" />
    <ProjectReference Include="..\..\Titanis.DceRpc\Titanis.DceRpc.csproj" />
  </ItemGroup>

</Project>
