using Fasp;
using MS_FASP;
using System.Data;
using System.Net.Sockets;
using System.Runtime.CompilerServices;
using Titanis.Asn1;
using Titanis.DceRpc;

namespace Titanis.Msrpc.Msfasp
{
	public enum FirewallRuleDirection
	{
		In = FW_DIRECTION.FW_DIR_IN,
		Out = FW_DIRECTION.FW_DIR_OUT,
	}
	public enum FirewallPortKeywords
	{
		None = FW_PORT_KEYWORD.FW_PORT_KEYWORD_NONE,
		DynamicRpc = FW_PORT_KEYWORD.FW_PORT_KEYWORD_DYNAMIC_RPC_PORTS,
		RpcEp = FW_PORT_KEYWORD.FW_PORT_KEYWORD_RPC_EP,
		Teredo = FW_PORT_KEYWORD.FW_PORT_KEYWORD_TEREDO_PORT,
		IpTlsIn = FW_PORT_KEYWORD.FW_PORT_KEYWORD_IP_TLS_IN,
		IpTlsOut = FW_PORT_KEYWORD.FW_PORT_KEYWORD_IP_TLS_OUT,
		Dhcp = FW_PORT_KEYWORD.FW_PORT_KEYWORD_DHCP,
		PlatoDiscovery = FW_PORT_KEYWORD.FW_PORT_KEYWORD_PLAYTO_DISCOVERY,
		Mdns = FW_PORT_KEYWORD.FW_PORT_KEYWORD_MDNS,
		Cortana = FW_PORT_KEYWORD.FW_PORT_KEYWORD_CORTANA_OUT,
		ProximalTcpCdp = FW_PORT_KEYWORD.FW_PORT_KEYWORD_PROXIMAL_TCP_CDP,
	}
	public enum FirewallRuleAction
	{
		Invalid = FW_RULE_ACTION.FW_RULE_ACTION_INVALID,
		AllowBypass = FW_RULE_ACTION.FW_RULE_ACTION_ALLOW_BYPASS,
		Block = FW_RULE_ACTION.FW_RULE_ACTION_BLOCK,
		Allow = FW_RULE_ACTION.FW_RULE_ACTION_ALLOW,
	}
	[Flags]
	public enum InterfaceTypes
	{
		All = 0,
		Lan = FW_INTERFACE_TYPE.FW_INTERFACE_TYPE_LAN,
		Wireless = FW_INTERFACE_TYPE.FW_INTERFACE_TYPE_WIRELESS,
		RemoteAccess = FW_INTERFACE_TYPE.FW_INTERFACE_TYPE_REMOTE_ACCESS,
	}
	public sealed class PortRange
	{
		public PortRange(ushort port)
		{
			StartPort = port;
			EndPort = port;
		}
		public PortRange(ushort startPort, ushort endPort)
		{
			StartPort = startPort;
			EndPort = endPort;
		}

		public ushort StartPort { get; }
		public ushort EndPort { get; }

		public sealed override string ToString() => (StartPort == EndPort) ? StartPort.ToString() : $"{StartPort}-{EndPort}";
	}

	enum IcmpType
	{
		EchoReply = 0,
		DestinationUnreachable = 3,
		SourceQuench = 4,
		Redirect = 5,
		AlternateHostAddress = 6,
		Echo = 8,
		RouterAdvertisement = 9,
		RouterSolicitation = 10,
		TimerExceeded = 11,
		ParameterProblem = 12,
		Timestamp = 13,
		TimestampReply = 14,
		InfoRequest = 15,
		InfoReply = 16,
		AddressMaskRequest = 17,
		AddressMaskReply = 18,
		Traceroute = 30,
		DatagramConversionError = 31,
		MobileHostRedirect = 32,
		WhereAreYouV6 = 33,
		IAmHereV6 = 34,
		MobileRegistrationRequest = 35,
		MobileRegistrationReply = 36,
		DomainNameRequest = 37,
		DomainNameReply = 38,
	}
	enum IcmpUnreachableCode
	{
		NetUnreachable = 0,
		HostUnreachable = 1,
		ProtocolUnreachable = 2,
		PortUnreachable = 3,
		FragmentationNeeded = 4,
		SourceRouteFailed = 5,
		DestinationNetworkUnknown = 6,
		DestinationHostUnknown = 7,
		SourceHostIsolated = 8,
		NetAdminProhibited = 9,
		HostAdminProhibited = 10,
		NetServiceUnreachable = 11,
		HostServiceUnreachable = 12,
		CommsAdminProhibited = 13,
		HostPrecedenceViolation = 14,
		PrecedenceCutoff = 15,
	}
	enum IcmpRedirectCode
	{
		Network = 0,
		Host = 1,
		TypeOfServiceNet = 2,
		TypeOfServiceHost = 3,
	}

	public record struct IcmpTypeCode(byte Type, ushort Code)
	{
		public override string ToString() =>
			((IcmpType)Type) switch
			{
				IcmpType.DestinationUnreachable => ((IcmpUnreachableCode)Code).ToString(),
				IcmpType.Redirect => $"Redirect:{((IcmpRedirectCode)Code).ToString()}",
				_ => $"{(IcmpType)Type}:{Code}"
			};
	}
	public sealed class IcmpTypeCodeList
	{
		public IcmpTypeCodeList(IcmpTypeCode[] typeCodes)
		{
			TypeCodes = typeCodes ?? [];
		}

		public IcmpTypeCode[] TypeCodes { get; }

		public sealed override string ToString() => string.Join(", ", TypeCodes.Select(r => r.ToString()));
	}

	public sealed class PortList
	{
		public PortList(FW_PORTS localPorts)
			: this((FW_PORT_KEYWORD)localPorts.wPortKeywords, localPorts.Ports)
		{
		}

		internal PortList(FW_PORT_KEYWORD keywords, FW_PORT_RANGE_LIST ranges)
		{
			Keywords = (FirewallPortKeywords)keywords;
			Ranges = ranges.pPorts?.value?.ConvertAll(r => new PortRange(r.wBegin, r.wEnd)) ?? [];
		}

		public FirewallPortKeywords Keywords { get; }
		public PortRange[] Ranges { get; }

		public sealed override string ToString() =>
			(Keywords != 0 && Ranges.Length > 0) ? $"{Keywords}, {string.Join(", ", Ranges.Select(r => r.ToString()))}"
			: (Keywords != 0) ? Keywords.ToString()
			: (Ranges != null) ? string.Join(", ", Ranges.Select(r => r.ToString()))
			: string.Empty;
	}
	public enum FirewallRuleOrigin
	{
		Invalid = FW_RULE_ORIGIN_TYPE.FW_RULE_ORIGIN_INVALID,
		Local = FW_RULE_ORIGIN_TYPE.FW_RULE_ORIGIN_LOCAL,
		GroupPolicy = FW_RULE_ORIGIN_TYPE.FW_RULE_ORIGIN_GP,
		Dynamic = FW_RULE_ORIGIN_TYPE.FW_RULE_ORIGIN_DYNAMIC,
		AutoGenerated = FW_RULE_ORIGIN_TYPE.FW_RULE_ORIGIN_AUTOGEN,
		Hardcoded = FW_RULE_ORIGIN_TYPE.FW_RULE_ORIGIN_HARDCODED,
		Mdm = FW_RULE_ORIGIN_TYPE.FW_RULE_ORIGIN_MDM,
		HostLocal = FW_RULE_ORIGIN_TYPE.FW_RULE_ORIGIN_HOST_LOCAL,
		HostGroupPolicy = FW_RULE_ORIGIN_TYPE.FW_RULE_ORIGIN_HOST_GP,
		HostDynamic = FW_RULE_ORIGIN_TYPE.FW_RULE_ORIGIN_HOST_DYNAMIC,
		HostMdm = FW_RULE_ORIGIN_TYPE.FW_RULE_ORIGIN_HOST_MDM,
	}

	[Flags]
	public enum FirewallRuleFlags
	{
		None = 0,

		Active = FW_RULE_FLAGS.FW_RULE_FLAGS_ACTIVE,
		Auth = FW_RULE_FLAGS.FW_RULE_FLAGS_AUTHENTICATE,
		AuthWithEncryption = FW_RULE_FLAGS.FW_RULE_FLAGS_AUTHENTICATE_WITH_ENCRYPTION,
		RoutableAddressTraverse = FW_RULE_FLAGS.FW_RULE_FLAGS_ROUTEABLE_ADDRS_TRAVERSE,
		LooseSourceMapped = FW_RULE_FLAGS.FW_RULE_FLAGS_LOOSE_SOURCE_MAPPED,
		AuthenticateWithNoEncapsulation = FW_RULE_FLAGS.FW_RULE_FLAGS_AUTH_WITH_NO_ENCAPSULATION,
		AuthWithEncNegotiate = FW_RULE_FLAGS.FW_RULE_FLAGS_AUTH_WITH_ENC_NEGOTIATE,
		RoutableAddressTraverseDeferApp = FW_RULE_FLAGS.FW_RULE_FLAGS_ROUTEABLE_ADDRS_TRAVERSE_DEFER_APP,
		RoutableAddressTraverseDeferUser = FW_RULE_FLAGS.FW_RULE_FLAGS_ROUTEABLE_ADDRS_TRAVERSE_DEFER_USER,
		AuthBypassOutbound = FW_RULE_FLAGS.FW_RULE_FLAGS_AUTHENTICATE_BYPASS_OUTBOUND,
		AllowProfileCrossing = FW_RULE_FLAGS.FW_RULE_FLAGS_ALLOW_PROFILE_CROSSING,
		LocalOnlyMapped = FW_RULE_FLAGS.FW_RULE_FLAGS_LOCAL_ONLY_MAPPED,
		LuaConditionalAce = FW_RULE_FLAGS.FW_RULE_FLAGS_LUA_CONDITIONAL_ACE,
		BindToInterface = FW_RULE_FLAGS.FW_RULE_FLAGS_BIND_TO_INTERFACE,

		// [MS-FASP] § 2.2.103 FW_RULE_FLAGS2
		// These are shifted into the high word
		//FW_RULE_FLAGS2_NONE = 0x0000_0000,
		SystemOsOnly = 0x0001_0000,
		GameOsOnly = 0x0002_0000,
		DevMode = 0x0004_0000,
		//FW_RULE_FLAGS_MAX_V2_26 = 0x0008_0000,
		//FW_RULE_FLAGS2_NOT_USED_VALUE_8 = 0x0008_0000,
		//FW_RULE_FLAGS2_NOT_USED_VALUE_16 = 0x0010_0000,
		//FW_RULE_FLAGS2_NOT_USED_VALUE_32 = 0x0020_0000,
		//FW_RULE_FLAGS2_NOT_USED_VALUE_64 = 0x0040_0000,
		CalloutAndAudit = 0x0080_0000,
		//FW_RULE_FLAGS2_NOT_USED_VALUE_256 = 0x0100_0000,
		//FW_RULE_FLAGS2_NOT_USED_VALUE_512 = 0x0200_0000,
		//FW_RULE_FLAGS2_NOT_USED_VALUE_1024 = 0x0400_0000,
		//FW_RULE_FLAGS2_MAX = 0x0800
	}

	public class FirewallRule
	{
		private static IcmpTypeCodeList? MakeIcmpTypeCodeList(RpcPointer<FW_ICMP_TYPE_CODE[]>? list) =>
			(list is null) ? null
			: new IcmpTypeCodeList(list.value.Select(r => new IcmpTypeCode(r.bType, r.wCode)).ToArray());

		public static implicit operator FirewallRule(in FW_RULE2_0 rule)
		{
			FirewallRule ruleInfo = new()
			{
				RuleId = rule.wszRuleId.value,
				SchemaVersion = rule.wSchemaVersion,
				Name = rule.wszName.value,
				Description = rule.wszDescription?.value,
				Action = (FirewallRuleAction)rule.Action,
				Profiles = (FirewallProfiles)rule.dwProfiles,
				Direction = (FirewallRuleDirection)rule.Direction,
				IpProtocol = (IpProtocolNumber)rule.wIpProtocol,
				LocalApplication = rule.wszLocalApplication?.value,
				LocalService = rule.wszLocalService?.value,
				Interfaces = rule.LocalInterfaceIds.pLUIDs?.value?.ToArray(),
				InterfaceTypes = (InterfaceTypes)rule.dwLocalInterfaceTypes,
				Status = (FirewallRuleStatus)rule.Status,
				RemoteMachines = rule.wszRemoteMachineAuthorizationList?.value,
				RemoteUsers = rule.wszRemoteUserAuthorizationList?.value,
				EmbeddedContext = rule.wszEmbeddedContext?.value,
				Origin = (FirewallRuleOrigin)rule.Origin,
				GpoName = rule.wszGPOName?.value,
				Flags = (FirewallRuleFlags)rule.wFlags,
			};
			ruleInfo.SetPortList(
				rule.wIpProtocol,
				rule.unnamed_1.__unnamed_0.LocalPorts,
				rule.unnamed_1.__unnamed_0.RemotePorts,
				rule.unnamed_1.V4TypeCodeList,
				rule.unnamed_1.V6TypeCodeList
				);
			return ruleInfo;
		}

		private void SetPortList(
			ushort protocol,
			in FW_PORTS localPorts,
			in FW_PORTS remotePorts,
			in FW_ICMP_TYPE_CODE_LIST icmp4,
			in FW_ICMP_TYPE_CODE_LIST icmp6
			)
		{
			switch ((IpProtocolNumber)protocol)
			{
				case IpProtocolNumber.Tcp or IpProtocolNumber.Udp:
					this.LocalPortList = new PortList(localPorts);
					this.RemotePortList = new PortList(remotePorts);
					break;
				case IpProtocolNumber.Icmp:
					this.IcmpTypeCodeList = MakeIcmpTypeCodeList(icmp4.pEntries);
					break;
				case IpProtocolNumber.IcmpV6:
					this.IcmpTypeCodeList = MakeIcmpTypeCodeList(icmp6.pEntries);
					break;
				default:
					break;
			}
		}

		public static implicit operator FirewallRule(in FW_RULE2_10 rule)
		{
			FirewallRule ruleInfo = new()
			{
				RuleId = rule.wszRuleId.value,
				SchemaVersion = rule.wSchemaVersion,
				Name = rule.wszName.value,
				Description = rule.wszDescription?.value,
				Action = (FirewallRuleAction)rule.Action,
				Profiles = (FirewallProfiles)rule.dwProfiles,
				Direction = (FirewallRuleDirection)rule.Direction,
				IpProtocol = (IpProtocolNumber)rule.wIpProtocol,
				LocalApplication = rule.wszLocalApplication?.value,
				LocalService = rule.wszLocalService?.value,
				Interfaces = rule.LocalInterfaceIds.pLUIDs?.value?.ToArray(),
				InterfaceTypes = (InterfaceTypes)rule.dwLocalInterfaceTypes,
				Status = (FirewallRuleStatus)rule.Status,
				RemoteMachines = rule.wszRemoteMachineAuthorizationList?.value,
				RemoteUsers = rule.wszRemoteUserAuthorizationList?.value,
				EmbeddedContext = rule.wszEmbeddedContext?.value,
				Origin = (FirewallRuleOrigin)rule.Origin,
				GpoName = rule.wszGPOName?.value,
				Flags = (FirewallRuleFlags)rule.wFlags,
				Metadata = CreateNewOnMetadata(rule.pMetaData)
			};
			ruleInfo.SetPortList(
				rule.wIpProtocol,
				rule.unnamed_1.__unnamed_0.LocalPorts,
				rule.unnamed_1.__unnamed_0.RemotePorts,
				rule.unnamed_1.V4TypeCodeList,
				rule.unnamed_1.V6TypeCodeList
				);
			return ruleInfo;
		}

		public static implicit operator FirewallRule(in FW_RULE2_20 rule)
		{
			FirewallRule ruleInfo = new()
			{
				RuleId = rule.wszRuleId.value,
				SchemaVersion = rule.wSchemaVersion,
				Name = rule.wszName.value,
				Description = rule.wszDescription?.value,
				Action = (FirewallRuleAction)rule.Action,
				Profiles = (FirewallProfiles)rule.dwProfiles,
				Direction = (FirewallRuleDirection)rule.Direction,
				IpProtocol = (IpProtocolNumber)rule.wIpProtocol,
				LocalApplication = rule.wszLocalApplication?.value,
				LocalService = rule.wszLocalService?.value,
				Interfaces = rule.LocalInterfaceIds.pLUIDs?.value?.ToArray(),
				InterfaceTypes = (InterfaceTypes)rule.dwLocalInterfaceTypes,
				Status = (FirewallRuleStatus)rule.Status,
				RemoteMachines = rule.wszRemoteMachineAuthorizationList?.value,
				RemoteUsers = rule.wszRemoteUserAuthorizationList?.value,
				EmbeddedContext = rule.wszEmbeddedContext?.value,
				Origin = (FirewallRuleOrigin)rule.Origin,
				GpoName = rule.wszGPOName?.value,
				Flags = (FirewallRuleFlags)rule.wFlags,
				Metadata = CreateNewOnMetadata(rule.pMetaData),
				LocalUserAuthorizationList = rule.wszLocalUserAuthorizationList?.value,
				PackageId = rule.wszPackageId?.value,
				LocalUserOwner = rule.wszLocalUserOwner?.value,
			};
			switch ((IpProtocolNumber)rule.wIpProtocol)
			{
				case IpProtocolNumber.Tcp or IpProtocolNumber.Udp:
					ruleInfo.LocalPortList = new PortList(rule.unnamed_1.__unnamed_0.LocalPorts);
					ruleInfo.RemotePortList = new PortList(rule.unnamed_1.__unnamed_0.RemotePorts);
					break;
				case IpProtocolNumber.Icmp:
					ruleInfo.IcmpTypeCodeList = MakeIcmpTypeCodeList(rule.unnamed_1.V4TypeCodeList.pEntries);
					break;
				case IpProtocolNumber.IcmpV6:
					ruleInfo.IcmpTypeCodeList = MakeIcmpTypeCodeList(rule.unnamed_1.V6TypeCodeList.pEntries);
					break;
				default:
					break;
			}
			return ruleInfo;
		}

		public static implicit operator FirewallRule(in FW_RULE2_24 rule)
		{
			FirewallRule ruleInfo = new()
			{
				RuleId = rule.wszRuleId.value,
				SchemaVersion = rule.wSchemaVersion,
				Name = rule.wszName.value,
				Description = rule.wszDescription?.value,
				Action = (FirewallRuleAction)rule.Action,
				Profiles = (FirewallProfiles)rule.dwProfiles,
				Direction = (FirewallRuleDirection)rule.Direction,
				IpProtocol = (IpProtocolNumber)rule.wIpProtocol,
				LocalApplication = rule.wszLocalApplication?.value,
				LocalService = rule.wszLocalService?.value,
				Interfaces = rule.LocalInterfaceIds.pLUIDs?.value?.ToArray(),
				InterfaceTypes = (InterfaceTypes)rule.dwLocalInterfaceTypes,
				Status = (FirewallRuleStatus)rule.Status,
				RemoteMachines = rule.wszRemoteMachineAuthorizationList?.value,
				RemoteUsers = rule.wszRemoteUserAuthorizationList?.value,
				EmbeddedContext = rule.wszEmbeddedContext?.value,
				Origin = (FirewallRuleOrigin)rule.Origin,
				GpoName = rule.wszGPOName?.value,
				Flags = (FirewallRuleFlags)rule.wFlags,
				Metadata = CreateNewOnMetadata(rule.pMetaData),
				LocalUserAuthorizationList = rule.wszLocalUserAuthorizationList?.value,
				PackageId = rule.wszPackageId?.value,
				LocalUserOwner = rule.wszLocalUserOwner?.value,
				TrustTupleKeywords = rule.dwTrustTupleKeywords,
				OnNetworkNames = rule.OnNetworkNames.wszNames?.value.UnwrapArray(),
				SecurityRealmId = rule.wszSecurityRealmId?.value
			};
			ruleInfo.SetPortList(
				rule.wIpProtocol,
				rule.unnamed_1.__unnamed_0.LocalPorts,
				rule.unnamed_1.__unnamed_0.RemotePorts,
				rule.unnamed_1.V4TypeCodeList,
				rule.unnamed_1.V6TypeCodeList
				);
			return ruleInfo;
		}

		public static implicit operator FirewallRule(in FW_RULE2_25 rule)
		{
			FirewallRule ruleInfo = new()
			{
				RuleId = rule.wszRuleId.value,
				SchemaVersion = rule.wSchemaVersion,
				Name = rule.wszName.value,
				Description = rule.wszDescription?.value,
				Action = (FirewallRuleAction)rule.Action,
				Profiles = (FirewallProfiles)rule.dwProfiles,
				Direction = (FirewallRuleDirection)rule.Direction,
				IpProtocol = (IpProtocolNumber)rule.wIpProtocol,
				LocalApplication = rule.wszLocalApplication?.value,
				LocalService = rule.wszLocalService?.value,
				Interfaces = rule.LocalInterfaceIds.pLUIDs?.value?.ToArray(),
				InterfaceTypes = (InterfaceTypes)rule.dwLocalInterfaceTypes,
				Status = (FirewallRuleStatus)rule.Status,
				RemoteMachines = rule.wszRemoteMachineAuthorizationList?.value,
				RemoteUsers = rule.wszRemoteUserAuthorizationList?.value,
				EmbeddedContext = rule.wszEmbeddedContext?.value,
				Origin = (FirewallRuleOrigin)rule.Origin,
				GpoName = rule.wszGPOName?.value,
				Flags = (FirewallRuleFlags)(rule.wFlags | (rule.wFlags2 << 16)),
				Metadata = CreateNewOnMetadata(rule.pMetaData),
				LocalUserAuthorizationList = rule.wszLocalUserAuthorizationList?.value,
				PackageId = rule.wszPackageId?.value,
				LocalUserOwner = rule.wszLocalUserOwner?.value,
				TrustTupleKeywords = rule.dwTrustTupleKeywords,
				OnNetworkNames = rule.OnNetworkNames.wszNames?.value.UnwrapArray(),
				SecurityRealmId = rule.wszSecurityRealmId?.value
			};
			ruleInfo.SetPortList(
				rule.wIpProtocol,
				rule.unnamed_1.__unnamed_0.LocalPorts,
				rule.unnamed_1.__unnamed_0.RemotePorts,
				rule.unnamed_1.V4TypeCodeList,
				rule.unnamed_1.V6TypeCodeList
				);
			return ruleInfo;
		}

		public static implicit operator FirewallRule(in FW_RULE2_26 rule)
		{
			FirewallRule ruleInfo = new()
			{
				RuleId = rule.wszRuleId.value,
				SchemaVersion = rule.wSchemaVersion,
				Name = rule.wszName.value,
				Description = rule.wszDescription?.value,
				Action = (FirewallRuleAction)rule.Action,
				Profiles = (FirewallProfiles)rule.dwProfiles,
				Direction = (FirewallRuleDirection)rule.Direction,
				IpProtocol = (IpProtocolNumber)rule.wIpProtocol,
				LocalApplication = rule.wszLocalApplication?.value,
				LocalService = rule.wszLocalService?.value,
				Interfaces = rule.LocalInterfaceIds.pLUIDs?.value?.ToArray(),
				InterfaceTypes = (InterfaceTypes)rule.dwLocalInterfaceTypes,
				Status = (FirewallRuleStatus)rule.Status,
				RemoteMachines = rule.wszRemoteMachineAuthorizationList?.value,
				RemoteUsers = rule.wszRemoteUserAuthorizationList?.value,
				EmbeddedContext = rule.wszEmbeddedContext?.value,
				Origin = (FirewallRuleOrigin)rule.Origin,
				GpoName = rule.wszGPOName?.value,
				Flags = (FirewallRuleFlags)(rule.wFlags | (rule.wFlags2 << 16)),
				Metadata = CreateNewOnMetadata(rule.pMetaData),
				LocalUserAuthorizationList = rule.wszLocalUserAuthorizationList?.value,
				PackageId = rule.wszPackageId?.value,
				LocalUserOwner = rule.wszLocalUserOwner?.value,
				TrustTupleKeywords = rule.dwTrustTupleKeywords,
				OnNetworkNames = rule.OnNetworkNames.wszNames?.value.UnwrapArray(),
				SecurityRealmId = rule.wszSecurityRealmId?.value,
				RemoteOutServerNames = rule.RemoteOutServerNames.wszNames?.value.UnwrapArray(),
			};
			ruleInfo.SetPortList(
				rule.wIpProtocol,
				rule.unnamed_1.__unnamed_0.LocalPorts,
				rule.unnamed_1.__unnamed_0.RemotePorts,
				rule.unnamed_1.V4TypeCodeList,
				rule.unnamed_1.V6TypeCodeList
				);
			return ruleInfo;
		}
		public static implicit operator FirewallRule(in FW_RULE2_27 rule)
		{
			FirewallRule ruleInfo = new()
			{
				RuleId = rule.wszRuleId.value,
				SchemaVersion = rule.wSchemaVersion,
				Name = rule.wszName.value,
				Description = rule.wszDescription?.value,
				Action = (FirewallRuleAction)rule.Action,
				Profiles = (FirewallProfiles)rule.dwProfiles,
				Direction = (FirewallRuleDirection)rule.Direction,
				IpProtocol = (IpProtocolNumber)rule.wIpProtocol,
				LocalApplication = rule.wszLocalApplication?.value,
				LocalService = rule.wszLocalService?.value,
				Interfaces = rule.LocalInterfaceIds.pLUIDs?.value?.ToArray(),
				InterfaceTypes = (InterfaceTypes)rule.dwLocalInterfaceTypes,
				Status = (FirewallRuleStatus)rule.Status,
				RemoteMachines = rule.wszRemoteMachineAuthorizationList?.value,
				RemoteUsers = rule.wszRemoteUserAuthorizationList?.value,
				EmbeddedContext = rule.wszEmbeddedContext?.value,
				Origin = (FirewallRuleOrigin)rule.Origin,
				GpoName = rule.wszGPOName?.value,
				Flags = (FirewallRuleFlags)(rule.wFlags | (rule.wFlags2 << 16)),
				Metadata = CreateNewOnMetadata(rule.pMetaData),
				LocalUserAuthorizationList = rule.wszLocalUserAuthorizationList?.value,
				PackageId = rule.wszPackageId?.value,
				LocalUserOwner = rule.wszLocalUserOwner?.value,
				TrustTupleKeywords = rule.dwTrustTupleKeywords,
				OnNetworkNames = rule.OnNetworkNames.wszNames?.value.UnwrapArray(),
				SecurityRealmId = rule.wszSecurityRealmId?.value,
				RemoteOutServerNames = rule.RemoteOutServerNames.wszNames?.value.UnwrapArray(),
				FullyQualifiedBinaryName = rule.wszFqbn?.value,
				CompartmentId = rule.compartmentId,
			};
			ruleInfo.SetPortList(
				rule.wIpProtocol,
				rule.unnamed_1.__unnamed_0.LocalPorts,
				rule.unnamed_1.__unnamed_0.RemotePorts,
				rule.unnamed_1.V4TypeCodeList,
				rule.unnamed_1.V6TypeCodeList
				);
			return ruleInfo;
		}
		public static implicit operator FirewallRule(in FW_RULE2_31 rule)
		{
			FirewallRule ruleInfo = new()
			{
				RuleId = rule.wszRuleId.value,
				SchemaVersion = rule.wSchemaVersion,
				Name = rule.wszName.value,
				Description = rule.wszDescription?.value,
				Action = (FirewallRuleAction)rule.Action,
				Profiles = (FirewallProfiles)rule.dwProfiles,
				Direction = (FirewallRuleDirection)rule.Direction,
				IpProtocol = (IpProtocolNumber)rule.wIpProtocol,
				LocalApplication = rule.wszLocalApplication?.value,
				LocalService = rule.wszLocalService?.value,
				Interfaces = rule.LocalInterfaceIds.pLUIDs?.value?.ToArray(),
				InterfaceTypes = (InterfaceTypes)rule.dwLocalInterfaceTypes,
				Status = (FirewallRuleStatus)rule.Status,
				RemoteMachines = rule.wszRemoteMachineAuthorizationList?.value,
				RemoteUsers = rule.wszRemoteUserAuthorizationList?.value,
				EmbeddedContext = rule.wszEmbeddedContext?.value,
				Origin = (FirewallRuleOrigin)rule.Origin,
				GpoName = rule.wszGPOName?.value,
				Flags = (FirewallRuleFlags)(rule.wFlags | (rule.wFlags2 << 16)),
				Metadata = CreateNewOnMetadata(rule.pMetaData),
				LocalUserAuthorizationList = rule.wszLocalUserAuthorizationList?.value,
				PackageId = rule.wszPackageId?.value,
				LocalUserOwner = rule.wszLocalUserOwner?.value,
				TrustTupleKeywords = rule.dwTrustTupleKeywords,
				OnNetworkNames = rule.OnNetworkNames.wszNames?.value.UnwrapArray(),
				SecurityRealmId = rule.wszSecurityRealmId?.value,
				RemoteOutServerNames = rule.RemoteOutServerNames.wszNames?.value.UnwrapArray(),
				FullyQualifiedBinaryName = rule.wszFqbn?.value,
				CompartmentId = rule.compartmentId,
				ProviderContextKey = rule.providerContextKey,
				RemoteDynamicKeywordAddresses = rule.RemoteDynamicKeywordAddresses.ids?.value
			};
			ruleInfo.SetPortList(
				rule.wIpProtocol,
				rule.unnamed_1.__unnamed_0.LocalPorts,
				rule.unnamed_1.__unnamed_0.RemotePorts,
				rule.unnamed_1.V4TypeCodeList,
				rule.unnamed_1.V6TypeCodeList
				);
			return ruleInfo;
		}

		private static FirewallObjectMetadata[] CreateNewOnMetadata(RpcPointer<FW_OBJECT_METADATA[]> pMetaData)
		{
			if (pMetaData is null)
				return null;

			return Array.ConvertAll(pMetaData.value, r =>
			{
				FW_ENFORCEMENT_STATE[]? enfStates = r.pEnforcementStates.value;
				return new FirewallObjectMetadata
				{
					FilterContextId = r.qwFilterContextID,
					EnforcementStateValues = (enfStates == null) ? null : Array.ConvertAll(enfStates, r => (EnforcementState)r)
				};
			});
		}

		public string? RuleId { get; set; }
		public ushort SchemaVersion { get; set; }
		public string? Name { get; set; }
		public string? Description { get; set; }
		public FirewallRuleAction Action { get; set; }
		public FirewallProfiles Profiles { get; set; }
		public FirewallRuleDirection Direction { get; set; }
		public IpProtocolNumber IpProtocol { get; set; }
		public PortList? LocalPortList { get; set; }
		public PortList? RemotePortList { get; set; }
		public string? LocalApplication { get; set; }
		public string? LocalService { get; set; }
		public Guid[]? Interfaces { get; set; }
		public InterfaceTypes InterfaceTypes { get; set; }
		public FirewallRuleStatus Status { get; set; }
		public string? RemoteMachines { get; set; }
		public string? RemoteUsers { get; set; }
		public string? EmbeddedContext { get; set; }
		public FirewallRuleOrigin Origin { get; set; }
		public string? GpoName { get; set; }
		public FirewallRuleFlags Flags { get; set; }
		public IcmpTypeCodeList? IcmpTypeCodeList { get; set; }
		// 2_10+
		public FirewallObjectMetadata[]? Metadata { get; set; }
		public EnforcementStates? EnforcementStates => this.Metadata?.Aggregate(Msfasp.EnforcementStates.None, (x, y) => x | y.EnforcementStates);

		public string? LocalUserAuthorizationList { get; set; }
		public string? PackageId { get; set; }
		public string? LocalUserOwner { get; set; }
		public uint TrustTupleKeywords { get; set; }
		public string[]? OnNetworkNames { get; set; }
		public string? SecurityRealmId { get; set; }
		public string[]? RemoteOutServerNames { get; private set; }
		public string? FullyQualifiedBinaryName { get; private set; }
		public uint CompartmentId { get; private set; }
		public Guid ProviderContextKey { get; private set; }
		public Guid[]? RemoteDynamicKeywordAddresses { get; private set; }
	}

	public enum EnforcementState : int
	{
		Invalid = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_INVALID,
		Full = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_FULL,
		FirewallOffInProfile = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_WF_OFF_IN_PROFILE,
		CategoryOff = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_CATEGORY_OFF,
		Disabled = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_DISABLED_OBJECT,
		InactiveProfile = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_INACTIVE_PROFILE,
		LocalAddressResolutionEmpty = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_LOCAL_ADDRESS_RESOLUTION_EMPTY,
		RemoteAddressResolutionEmpty = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_REMOTE_ADDRESS_RESOLUTION_EMPTY,
		LocalPortResolutionEmpty = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_LOCAL_PORT_RESOLUTION_EMPTY,
		RemotePortResolutionEmpty = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_REMOTE_PORT_RESOLUTION_EMPTY,
		InterfaceResolutionEmpty = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_INTERFACE_RESOLUTION_EMPTY,
		ApplicationResolutionEmpty = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_APPLICATION_RESOLUTION_EMPTY,
		RemoteMachineEmpty = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_REMOTE_MACHINE_EMPTY,
		RemoteUserEmpty = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_REMOTE_USER_EMPTY,
		LocalGlobalOpenPortsDisallowed = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_LOCAL_GLOBAL_OPEN_PORTS_DISALLOWED,
		LocalAuthorizedApplicationsDisallowed = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_LOCAL_AUTHORIZED_APPLICATIONS_DISALLOWED,
		LocalFirewallRulesDisallowed = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_LOCAL_FIREWALL_RULES_DISALLOWED,
		LocalConnSecRulesDisallowed = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_LOCAL_CONSEC_RULES_DISALLOWED,
		MismatchedPlatform = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_MISMATCHED_PLATFORM,
		OptimizedOut = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_OPTIMIZED_OUT,
		LocalUserEmpty = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_LOCAL_USER_EMPTY,
		TransportMachineSdEmpty = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_TRANSPORT_MACHINE_SD_EMPTY,
		TransportUserSdEmpty = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_TRANSPORT_USER_SD_EMPTY,
		TupleResolutionEmpty = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_TUPLE_RESOLUTION_EMPTY,
		NetNameResolutionEmpty = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_NETNAME_RESOLUTION_EMPTY,
		Duplicate = FW_ENFORCEMENT_STATE.FW_ENFORCEMENT_STATE_DUPLICATE,
	}

	[Flags]
	public enum EnforcementStates : uint
	{
		None = 0,
		Invalid = (1U << EnforcementState.Invalid),
		Full = (1U << EnforcementState.Full),
		FirewallOffInProfile = (1U << EnforcementState.FirewallOffInProfile),
		CategoryOff = (1U << EnforcementState.CategoryOff),
		Disabled = (1U << EnforcementState.Disabled),
		InactiveProfile = (1U << EnforcementState.InactiveProfile),
		LocalAddressResolutionEmpty = (1U << EnforcementState.LocalAddressResolutionEmpty),
		RemoteAddressResolutionEmpty = (1U << EnforcementState.RemoteAddressResolutionEmpty),
		LocalPortResolutionEmpty = (1U << EnforcementState.LocalPortResolutionEmpty),
		RemotePortResolutionEmpty = (1U << EnforcementState.RemotePortResolutionEmpty),
		InterfaceResolutionEmpty = (1U << EnforcementState.InterfaceResolutionEmpty),
		ApplicationResolutionEmpty = (1U << EnforcementState.ApplicationResolutionEmpty),
		RemoteMachineEmpty = (1U << EnforcementState.RemoteMachineEmpty),
		RemoteUserEmpty = (1U << EnforcementState.RemoteUserEmpty),
		LocalGlobalOpenPortsDisallowed = (1U << EnforcementState.LocalGlobalOpenPortsDisallowed),
		LocalAuthorizedApplicationsDisallowed = (1U << EnforcementState.LocalAuthorizedApplicationsDisallowed),
		LocalFirewallRulesDisallowed = (1U << EnforcementState.LocalFirewallRulesDisallowed),
		LocalConnSecRulesDisallowed = (1U << EnforcementState.LocalConnSecRulesDisallowed),
		MismatchedPlatform = (1U << EnforcementState.MismatchedPlatform),
		OptimizedOut = (1U << EnforcementState.OptimizedOut),
		LocalUserEmpty = (1U << EnforcementState.LocalUserEmpty),
		TransportMachineSdEmpty = (1U << EnforcementState.TransportMachineSdEmpty),
		TransportUserSdEmpty = (1U << EnforcementState.TransportUserSdEmpty),
		TupleResolutionEmpty = (1U << EnforcementState.TupleResolutionEmpty),
		NetNameResolutionEmpty = (1U << EnforcementState.NetNameResolutionEmpty),
		Duplicate = (1U << EnforcementState.Duplicate),
	}
	public class FirewallObjectMetadata
	{
		public ulong FilterContextId { get; set; }
		public EnforcementState[]? EnforcementStateValues { get; set; }
		public EnforcementStates EnforcementStates => (EnforcementStateValues == null) ? 0 : (this.EnforcementStateValues.Aggregate(EnforcementStates.None, (x, y) => x | (EnforcementStates)(1U << (int)y)));
	}
}