namespace Titanis.Winterop
{
	// [MS-FSCC] § 2.4 File Information Classes
	public enum FileInfoClass : byte
	{
		AccessInfo = 8,
		AlignmentInfo = 17,
		AllInfo = 18,
		AllocationInfo = 19,
		AlternateNameInfo = 21,
		AttributeTagInfo = 35,
		BasicInfo = 4,
		BothDirectoryInfo = 3,
		CompressionInfo = 28,
		DirectoryInfo = 1,
		DispositionInfo = 13,
		EaInfo = 7,
		EndOfFileInfo = 20,
		FullDirectoryInfo = 2,
		FullEaInfo = 15,
		HardLinkInfo = 46,
		IdBothDirectoryInfo = 37,
		IdExtendedDirectoryInfo = 60,
		IdFullDirectoryInfo = 38,
		GlobalTxDirectoryInfo = 50,
		IdInfo = 59,
		InternalInfo = 6,
		LinkInfo = 11,
		MailslotQueryInfo = 26,
		MailslotSetInfo = 27,
		ModeInfo = 16,
		MoveClusterInfo = 31,
		NameInfo = 9,
		NamesInfo = 12,
		NetworkOpenInfo = 34,
		NormalizedNameInfo = 48,
		ObjectIdInfo = 29,
		PipeInfo = 23,
		PipeLocalInfo = 24,
		PipeRemoteInfo = 25,
		PositionInfo = 14,
		QuotaInfo = 32,
		RenameInfo = 10,
		ReparsePointInfo = 33,
		SfioReserveInfo = 44,
		SfioVolumeInfo = 45,
		ShortNameInfo = 40,
		StandardInfo = 5,
		StandardLinkInfo = 54,
		FileStreamInfo = 22,
		TrackingInfo = 36,

		ValidDataLengthInfo = 39,

		FsControlInfo = 6,
		FsObjectIdInfo = 8,
	}
}
