#!/bin/bash

_comp_T_param() {
	local paramSpec=$1
	local cmp=$2

	local paramName paramType rest
	IFS=":" read -r paramName paramType rest <<< "$paramSpec"

	if [[ -z "$paramType" ]]; then
		# No completions available

		local pvname="TITANIS_PVLIST_${paramName^^}[@]"
		if [[ -n $pvname ]]; then
			local pv
			for pv in "${!pvname}"; do
				if [[ $pv = ^* ]]; then
					pv=${pv#^}
					declare -a pvparts
					IFS=";" read -r -a pvparts <<< $pv
					local pvfile="${pvparts[0]}"
					local -i pvfield=${pvparts[1]}
					local pvdelim="${pvparts[2]}"
					if [[ -z $pvdelim ]]; then
						pvdelim="$IFS"
					fi

					if [[ -f $pvfile ]]; then
						if [[ $pvfield = 0 ]]; then
							local fileline
							while IFS= read -r fileline; do
								if [[ $fileline != \#* ]]; then
									COMPREPLY+=( "$fileline" )
								fi
							done < $pvfile
						else
							declare -a filevalues
							((pvfield--))
							while IFS="$pvdelim" read -r -a filevalues; do
								if [[ $filevalues != \#* ]]; then
									COMPREPLY+=( "${filevalues[$pvfield]}" )
								fi
							done < $pvfile
						fi
					fi
				else
					COMPREPLY+=( "$pv" )
				fi
			done
			_T_filterArray "$cmp" "${COMPREPLY[@]}"
			return 0
		else
			COMPREPLY=()
			return 1
		fi
	fi


	if [[ "$paramType" = "list" ]]; then
		IFS=";" read -r -a COMPREPLY <<< $rest
		_T_filterArray "$cmp" "${COMPREPLY[@]}"
		return 0
	elif [[ "$paramType" = "file" ]]; then
		declare -a filePatterns
		IFS=";" read -r -a filePatterns <<< $rest
		COMPREPLY=()
		for i in "${filePatterns[@]}"; do
			COMPREPLY+=( $(compgen -G "$cmp$i") )
		done
		return 0
	else
		local pvname="TITANIS_PVLIST_$paramName"
		COMPREPLY=( $(compgen -A "$paramType" "$cmp") )
		return 0
	fi
}

_T_filterArray() {
	local pattern=$1
	if [[ -z $pattern ]]; then
		COMPREPLY=(${@:2})
		return 0
	fi

	local matching=()
	local i
	for i in ${@:2}; do
		if [[ -z $pattern || ${i,,} = ${pattern,,}* ]]; then
			matching+=($i)
		fi
	done

	COMPREPLY=(${matching[@]})

	return 0
}

_comp_Titanis() {
	# Expect -A params and -a paramsByPos
	local args=( "${COMP_WORDS[@]:1}" )
	local argCount=${#args[@]}
	local -i targetArgIndex=$((COMP_CWORD - 1))

	if [[ "${COMP_LINE:(COMP_POINT-1):2}" == " " ]]; then
		# Cursor is at the end of the line
		#((targetArgIndex++))
		:
	fi

	local curArg="${args[$targetArgIndex]}"
	if [[ $curArg == -* ]]; then
		# Cursor is on a parameter name
		# Filter parameter names to exclude used parameters
		declare -A usedParams
		for arg in ${args[@]}; do
			usedParams+=( ["${arg,,}"]=true )
		done

		declare -a availParams
		local paramName
		for paramName in "${!params[@]}"; do
			local paramSpec=${params[$paramName]}
			local paramType rest
			IFS=':' read -r paramName paramType rest <<< "$paramSpec"

			if [[ ! -v usedParams["-${paramName,,}"] ]]; then
				availParams+=("-${paramName}")
			fi
		done

		_T_filterArray "$curArg" ${availParams[@]}
		return 0;
	fi

	local -i nextPos=0
	local i
	local selArgName=""
	local -i isPos=0
	declare -A argValues
	local argName=""
	for ((i=0; i<=$targetArgIndex; i++)); do
		local arg=${args[i]}
		isPos=0

		if [[ $arg = -* ]]; then
			argName=$arg
		elif [[ $arg = *, ]]; then
			# Keep the same arg name
			:
		elif [[ -n "$argName" ]]; then
			# Consume this named argument
			selArgName=$argName
			argValues+=( ["${selArgName,,}"]="$arg" )
			argName=""
		else
			while true; do
				selArgName="-${paramsByPos[nextPos]}"
				((nextPos++))

				if [[ ! -v argValues["${selArgName,,}"] ]]; then
					isPos=1
					break
				fi
			done
		fi
	done

	if [[ -n $selArgName ]]; then
		if [[ $isPos -gt 0 && -z $curArg ]]; then
			# Help the user by printing the name of the positional argument
			COMPREPLY=( "$selArgName" )
			return 0
		else
			local argSpec=${params[${selArgName,,}]}
			_comp_T_param "$argSpec" "$curArg"
		fi
	else
		# No completion available
		return 1
	fi
}

_comp_T_subcommands() {
	local base=${COMP_WORDS[0]}
	local -a subcmds=( ${@:3} )
	local cmp=$2

	if [ $COMP_CWORD -eq 1 ]; then
		_T_filterArray "$cmp" "${subcmds[@]}"
	else
		local subcmd="${COMP_WORDS[1]}"
		((COMP_CWORD--))
		COMP_WORDS=( "${base}_${subcmd}" "${COMP_WORDS[@]:2}" )
		_${base}_$subcmd $base $cmp
	fi
	return 0
}
