#!/bin/bash

# Sam
_comp_Sam () {
	_comp_T_subcommands "$1" "$2" aliasmembers enumaliases enumgroups enumusers
	return $?
}
complete -F _comp_Sam Sam

# Sam aliasmembers
_comp_Sam_aliasmembers () {
	declare -A params=(
		['-aliasridorname']=$'AliasRidOrName::'
		['-continueonerror']=$'ContinueOnError::'
		['-servername']=$'ServerName::'
		['-consoleoutputstyle']=$'ConsoleOutputStyle:list:Freeform;Raw;Table;List;Csv;Tsv;Json;TreeTable'
		['-outputfields']=$'OutputFields:list:DomainName;DomainSid;GroupName;GroupRid;MemberSid;MemberName'
		['-outputheaders']=$'OutputHeaders::'
		['-loglevel']=$'LogLevel:list:Debug;Diagnostic;Verbose;Info;Warning;Error;Critical'
		['-consolelogformat']=$'ConsoleLogFormat:list:Text;TextWithTimestamp;Json'
		['-verbose']=$'Verbose::'
		['-diagnostic']=$'Diagnostic::'
		['-debuglog']=$'DebugLog::'
		['-humanreadable']=$'HumanReadable::'
		['-rpcconnecttimeout']=$'RpcConnectTimeout::'
		['-rpccalltimeout']=$'RpcCallTimeout::'
		['-spnego']=$'Spnego::'
		['-authepm']=$'AuthEpm::'
		['-encryptepm']=$'EncryptEpm::'
		['-encryptrpc']=$'EncryptRpc::'
		['-prefersmb']=$'PreferSmb::'
		['-anonymous']=$'Anonymous::'
		['-username']=$'UserName::'
		['-userdomain']=$'UserDomain::'
		['-password']=$'Password::'
		['-ntlmhash']=$'NtlmHash::'
		['-aeskey']=$'AesKey::'
		['-deskey']=$'DesKey::'
		['-workstation']=$'Workstation::'
		['-tgt']=$'Tgt::'
		['-armorticket']=$'ArmorTicket::'
		['-tickets']=$'Tickets::'
		['-ticketcache']=$'TicketCache::'
		['-delegate']=$'Delegate::'
		['-delegateticket']=$'DelegateTicket::'
		['-ntlmversion']=$'NtlmVersion::'
		['-kdc']=$'Kdc::'
		['-keytab']=$'Keytab::'
		['-s4username']=$'S4UserName::'
		['-u2username']=$'U2UserName::'
		['-s4usercert']=$'S4UserCert::'
		['-s4proxyservice']=$'S4ProxyService::'
		['-spnoverride']=$'SpnOverride::'
		['-authproxy']=$'AuthProxy::'
		['-hostaddress']=$'HostAddress::'
		['-usetcp6only']=$'UseTcp6Only::'
		['-usetcp4only']=$'UseTcp4Only::'
		['-socks5']=$'Socks5::'
		['-dialects']=$'Dialects:list:Smb2_0_2;Smb2_1;Smb3_0;Smb3_0_2;Smb3_1_1'
		['-requiresigning']=$'RequireSigning::'
		['-requiresecurenegotiate']=$'RequireSecureNegotiate::'
		['-encryptsmb']=$'EncryptSmb::'
		['-followdfs']=$'FollowDfs::'
		['-dfsreferralbuffersize']=$'DfsReferralBufferSize::'
		['-usercert']=$'UserCert::'
		['-userkey']=$'UserKey::'
		['-userkeypassword']=$'UserKeyPassword::'
	)
	declare -a paramsByPos=(
		'ServerName'
		'AliasRidOrName'
	)
	_comp_Titanis
}
complete -F _comp_Sam_aliasmembers Sam-aliasmembers

# Sam enumaliases
_comp_Sam_enumaliases () {
	declare -A params=(
		['-continueonerror']=$'ContinueOnError::'
		['-servername']=$'ServerName::'
		['-consoleoutputstyle']=$'ConsoleOutputStyle:list:Freeform;Raw;Table;List;Csv;Tsv;Json;TreeTable'
		['-outputfields']=$'OutputFields:list:AccountName;Domain;AccountType;Id;Sid;MemberCount;AdminComment'
		['-outputheaders']=$'OutputHeaders::'
		['-loglevel']=$'LogLevel:list:Debug;Diagnostic;Verbose;Info;Warning;Error;Critical'
		['-consolelogformat']=$'ConsoleLogFormat:list:Text;TextWithTimestamp;Json'
		['-verbose']=$'Verbose::'
		['-diagnostic']=$'Diagnostic::'
		['-debuglog']=$'DebugLog::'
		['-humanreadable']=$'HumanReadable::'
		['-rpcconnecttimeout']=$'RpcConnectTimeout::'
		['-rpccalltimeout']=$'RpcCallTimeout::'
		['-spnego']=$'Spnego::'
		['-authepm']=$'AuthEpm::'
		['-encryptepm']=$'EncryptEpm::'
		['-encryptrpc']=$'EncryptRpc::'
		['-prefersmb']=$'PreferSmb::'
		['-anonymous']=$'Anonymous::'
		['-username']=$'UserName::'
		['-userdomain']=$'UserDomain::'
		['-password']=$'Password::'
		['-ntlmhash']=$'NtlmHash::'
		['-aeskey']=$'AesKey::'
		['-deskey']=$'DesKey::'
		['-workstation']=$'Workstation::'
		['-tgt']=$'Tgt::'
		['-armorticket']=$'ArmorTicket::'
		['-tickets']=$'Tickets::'
		['-ticketcache']=$'TicketCache::'
		['-delegate']=$'Delegate::'
		['-delegateticket']=$'DelegateTicket::'
		['-ntlmversion']=$'NtlmVersion::'
		['-kdc']=$'Kdc::'
		['-keytab']=$'Keytab::'
		['-s4username']=$'S4UserName::'
		['-u2username']=$'U2UserName::'
		['-s4usercert']=$'S4UserCert::'
		['-s4proxyservice']=$'S4ProxyService::'
		['-spnoverride']=$'SpnOverride::'
		['-authproxy']=$'AuthProxy::'
		['-hostaddress']=$'HostAddress::'
		['-usetcp6only']=$'UseTcp6Only::'
		['-usetcp4only']=$'UseTcp4Only::'
		['-socks5']=$'Socks5::'
		['-dialects']=$'Dialects:list:Smb2_0_2;Smb2_1;Smb3_0;Smb3_0_2;Smb3_1_1'
		['-requiresigning']=$'RequireSigning::'
		['-requiresecurenegotiate']=$'RequireSecureNegotiate::'
		['-encryptsmb']=$'EncryptSmb::'
		['-followdfs']=$'FollowDfs::'
		['-dfsreferralbuffersize']=$'DfsReferralBufferSize::'
		['-usercert']=$'UserCert::'
		['-userkey']=$'UserKey::'
		['-userkeypassword']=$'UserKeyPassword::'
	)
	declare -a paramsByPos=(
		'ServerName'
	)
	_comp_Titanis
}
complete -F _comp_Sam_enumaliases Sam-enumaliases

# Sam enumgroups
_comp_Sam_enumgroups () {
	declare -A params=(
		['-continueonerror']=$'ContinueOnError::'
		['-servername']=$'ServerName::'
		['-consoleoutputstyle']=$'ConsoleOutputStyle:list:Freeform;Raw;Table;List;Csv;Tsv;Json;TreeTable'
		['-outputfields']=$'OutputFields:list:AccountName;Domain;AccountType;Id;Sid;Attributes;MemberCount;AdminComment'
		['-outputheaders']=$'OutputHeaders::'
		['-loglevel']=$'LogLevel:list:Debug;Diagnostic;Verbose;Info;Warning;Error;Critical'
		['-consolelogformat']=$'ConsoleLogFormat:list:Text;TextWithTimestamp;Json'
		['-verbose']=$'Verbose::'
		['-diagnostic']=$'Diagnostic::'
		['-debuglog']=$'DebugLog::'
		['-humanreadable']=$'HumanReadable::'
		['-rpcconnecttimeout']=$'RpcConnectTimeout::'
		['-rpccalltimeout']=$'RpcCallTimeout::'
		['-spnego']=$'Spnego::'
		['-authepm']=$'AuthEpm::'
		['-encryptepm']=$'EncryptEpm::'
		['-encryptrpc']=$'EncryptRpc::'
		['-prefersmb']=$'PreferSmb::'
		['-anonymous']=$'Anonymous::'
		['-username']=$'UserName::'
		['-userdomain']=$'UserDomain::'
		['-password']=$'Password::'
		['-ntlmhash']=$'NtlmHash::'
		['-aeskey']=$'AesKey::'
		['-deskey']=$'DesKey::'
		['-workstation']=$'Workstation::'
		['-tgt']=$'Tgt::'
		['-armorticket']=$'ArmorTicket::'
		['-tickets']=$'Tickets::'
		['-ticketcache']=$'TicketCache::'
		['-delegate']=$'Delegate::'
		['-delegateticket']=$'DelegateTicket::'
		['-ntlmversion']=$'NtlmVersion::'
		['-kdc']=$'Kdc::'
		['-keytab']=$'Keytab::'
		['-s4username']=$'S4UserName::'
		['-u2username']=$'U2UserName::'
		['-s4usercert']=$'S4UserCert::'
		['-s4proxyservice']=$'S4ProxyService::'
		['-spnoverride']=$'SpnOverride::'
		['-authproxy']=$'AuthProxy::'
		['-hostaddress']=$'HostAddress::'
		['-usetcp6only']=$'UseTcp6Only::'
		['-usetcp4only']=$'UseTcp4Only::'
		['-socks5']=$'Socks5::'
		['-dialects']=$'Dialects:list:Smb2_0_2;Smb2_1;Smb3_0;Smb3_0_2;Smb3_1_1'
		['-requiresigning']=$'RequireSigning::'
		['-requiresecurenegotiate']=$'RequireSecureNegotiate::'
		['-encryptsmb']=$'EncryptSmb::'
		['-followdfs']=$'FollowDfs::'
		['-dfsreferralbuffersize']=$'DfsReferralBufferSize::'
		['-usercert']=$'UserCert::'
		['-userkey']=$'UserKey::'
		['-userkeypassword']=$'UserKeyPassword::'
	)
	declare -a paramsByPos=(
		'ServerName'
	)
	_comp_Titanis
}
complete -F _comp_Sam_enumgroups Sam-enumgroups

# Sam enumusers
_comp_Sam_enumusers () {
	declare -A params=(
		['-continueonerror']=$'ContinueOnError::'
		['-servername']=$'ServerName::'
		['-consoleoutputstyle']=$'ConsoleOutputStyle:list:Freeform;Raw;Table;List;Csv;Tsv;Json;TreeTable'
		['-outputfields']=$'OutputFields:list:AccountName;Domain;AccountType;Id;Sid;FullName;AdminComment;PasswordLastSet;LastLogon;BadPasswordCount'
		['-outputheaders']=$'OutputHeaders::'
		['-loglevel']=$'LogLevel:list:Debug;Diagnostic;Verbose;Info;Warning;Error;Critical'
		['-consolelogformat']=$'ConsoleLogFormat:list:Text;TextWithTimestamp;Json'
		['-verbose']=$'Verbose::'
		['-diagnostic']=$'Diagnostic::'
		['-debuglog']=$'DebugLog::'
		['-humanreadable']=$'HumanReadable::'
		['-rpcconnecttimeout']=$'RpcConnectTimeout::'
		['-rpccalltimeout']=$'RpcCallTimeout::'
		['-spnego']=$'Spnego::'
		['-authepm']=$'AuthEpm::'
		['-encryptepm']=$'EncryptEpm::'
		['-encryptrpc']=$'EncryptRpc::'
		['-prefersmb']=$'PreferSmb::'
		['-anonymous']=$'Anonymous::'
		['-username']=$'UserName::'
		['-userdomain']=$'UserDomain::'
		['-password']=$'Password::'
		['-ntlmhash']=$'NtlmHash::'
		['-aeskey']=$'AesKey::'
		['-deskey']=$'DesKey::'
		['-workstation']=$'Workstation::'
		['-tgt']=$'Tgt::'
		['-armorticket']=$'ArmorTicket::'
		['-tickets']=$'Tickets::'
		['-ticketcache']=$'TicketCache::'
		['-delegate']=$'Delegate::'
		['-delegateticket']=$'DelegateTicket::'
		['-ntlmversion']=$'NtlmVersion::'
		['-kdc']=$'Kdc::'
		['-keytab']=$'Keytab::'
		['-s4username']=$'S4UserName::'
		['-u2username']=$'U2UserName::'
		['-s4usercert']=$'S4UserCert::'
		['-s4proxyservice']=$'S4ProxyService::'
		['-spnoverride']=$'SpnOverride::'
		['-authproxy']=$'AuthProxy::'
		['-hostaddress']=$'HostAddress::'
		['-usetcp6only']=$'UseTcp6Only::'
		['-usetcp4only']=$'UseTcp4Only::'
		['-socks5']=$'Socks5::'
		['-dialects']=$'Dialects:list:Smb2_0_2;Smb2_1;Smb3_0;Smb3_0_2;Smb3_1_1'
		['-requiresigning']=$'RequireSigning::'
		['-requiresecurenegotiate']=$'RequireSecureNegotiate::'
		['-encryptsmb']=$'EncryptSmb::'
		['-followdfs']=$'FollowDfs::'
		['-dfsreferralbuffersize']=$'DfsReferralBufferSize::'
		['-usercert']=$'UserCert::'
		['-userkey']=$'UserKey::'
		['-userkeypassword']=$'UserKeyPassword::'
	)
	declare -a paramsByPos=(
		'ServerName'
	)
	_comp_Titanis
}
complete -F _comp_Sam_enumusers Sam-enumusers
