#!/bin/bash

# Ldap
_comp_Ldap () {
	_comp_T_subcommands "$1" "$2" add addcomputer addou adduser listsyntax lspart mod moduser mountfs namedbits query rm schema search timestamp watch whoami
	return $?
}
complete -F _comp_Ldap Ldap

# Ldap add
_comp_Ldap_add () {
	declare -A params=(
		['-objectclass']=$'ObjectClass::'
		['-attributes']=$'Attributes::'
		['-objectname']=$'ObjectName::'
		['-servername']=$'ServerName::'
		['-gc']=$'Gc::'
		['-ssl']=$'Ssl::'
		['-sslcert']=$'SslCert::'
		['-sslkeyfile']=$'SslKeyFile::'
		['-sslkeypassword']=$'SslKeyPassword::'
		['-consoleoutputstyle']=$'ConsoleOutputStyle:list:Freeform;Raw;Table;List;Csv;Tsv;Json;TreeTable'
		['-outputheaders']=$'OutputHeaders::'
		['-loglevel']=$'LogLevel:list:Debug;Diagnostic;Verbose;Info;Warning;Error;Critical'
		['-consolelogformat']=$'ConsoleLogFormat:list:Text;TextWithTimestamp;Json'
		['-verbose']=$'Verbose::'
		['-diagnostic']=$'Diagnostic::'
		['-debuglog']=$'DebugLog::'
		['-humanreadable']=$'HumanReadable::'
		['-anonymous']=$'Anonymous::'
		['-username']=$'UserName::'
		['-userdomain']=$'UserDomain::'
		['-password']=$'Password::'
		['-ntlmhash']=$'NtlmHash::'
		['-aeskey']=$'AesKey::'
		['-deskey']=$'DesKey::'
		['-workstation']=$'Workstation::'
		['-tgt']=$'Tgt::'
		['-armorticket']=$'ArmorTicket::'
		['-tickets']=$'Tickets::'
		['-ticketcache']=$'TicketCache::'
		['-delegate']=$'Delegate::'
		['-delegateticket']=$'DelegateTicket::'
		['-ntlmversion']=$'NtlmVersion::'
		['-kdc']=$'Kdc::'
		['-keytab']=$'Keytab::'
		['-s4username']=$'S4UserName::'
		['-u2username']=$'U2UserName::'
		['-s4usercert']=$'S4UserCert::'
		['-s4proxyservice']=$'S4ProxyService::'
		['-spnoverride']=$'SpnOverride::'
		['-authproxy']=$'AuthProxy::'
		['-hostaddress']=$'HostAddress::'
		['-usetcp6only']=$'UseTcp6Only::'
		['-usetcp4only']=$'UseTcp4Only::'
		['-socks5']=$'Socks5::'
		['-usercert']=$'UserCert::'
		['-userkey']=$'UserKey::'
		['-userkeypassword']=$'UserKeyPassword::'
	)
	declare -a paramsByPos=(
		'ServerName'
		'ObjectName'
		'ObjectClass'
	)
	_comp_Titanis
}
complete -F _comp_Ldap_add Ldap-add

# Ldap addcomputer
_comp_Ldap_addcomputer () {
	declare -A params=(
		['-newpassword']=$'NewPassword::'
		['-logonname']=$'LogonName::'
		['-displayname']=$'DisplayName::'
		['-usercerts']=$'UserCerts::'
		['-os']=$'Os::'
		['-osversion']=$'OsVersion::'
		['-memberof']=$'MemberOf::'
		['-attributes']=$'Attributes::'
		['-objectname']=$'ObjectName::'
		['-servername']=$'ServerName::'
		['-gc']=$'Gc::'
		['-ssl']=$'Ssl::'
		['-sslcert']=$'SslCert::'
		['-sslkeyfile']=$'SslKeyFile::'
		['-sslkeypassword']=$'SslKeyPassword::'
		['-consoleoutputstyle']=$'ConsoleOutputStyle:list:Freeform;Raw;Table;List;Csv;Tsv;Json;TreeTable'
		['-outputheaders']=$'OutputHeaders::'
		['-loglevel']=$'LogLevel:list:Debug;Diagnostic;Verbose;Info;Warning;Error;Critical'
		['-consolelogformat']=$'ConsoleLogFormat:list:Text;TextWithTimestamp;Json'
		['-verbose']=$'Verbose::'
		['-diagnostic']=$'Diagnostic::'
		['-debuglog']=$'DebugLog::'
		['-humanreadable']=$'HumanReadable::'
		['-anonymous']=$'Anonymous::'
		['-username']=$'UserName::'
		['-userdomain']=$'UserDomain::'
		['-password']=$'Password::'
		['-ntlmhash']=$'NtlmHash::'
		['-aeskey']=$'AesKey::'
		['-deskey']=$'DesKey::'
		['-workstation']=$'Workstation::'
		['-tgt']=$'Tgt::'
		['-armorticket']=$'ArmorTicket::'
		['-tickets']=$'Tickets::'
		['-ticketcache']=$'TicketCache::'
		['-delegate']=$'Delegate::'
		['-delegateticket']=$'DelegateTicket::'
		['-ntlmversion']=$'NtlmVersion::'
		['-kdc']=$'Kdc::'
		['-keytab']=$'Keytab::'
		['-s4username']=$'S4UserName::'
		['-u2username']=$'U2UserName::'
		['-s4usercert']=$'S4UserCert::'
		['-s4proxyservice']=$'S4ProxyService::'
		['-spnoverride']=$'SpnOverride::'
		['-authproxy']=$'AuthProxy::'
		['-hostaddress']=$'HostAddress::'
		['-usetcp6only']=$'UseTcp6Only::'
		['-usetcp4only']=$'UseTcp4Only::'
		['-socks5']=$'Socks5::'
		['-usercert']=$'UserCert::'
		['-userkey']=$'UserKey::'
		['-userkeypassword']=$'UserKeyPassword::'
	)
	declare -a paramsByPos=(
		'ServerName'
		'ObjectName'
	)
	_comp_Titanis
}
complete -F _comp_Ldap_addcomputer Ldap-addcomputer

# Ldap addou
_comp_Ldap_addou () {
	declare -A params=(
		['-attributes']=$'Attributes::'
		['-objectname']=$'ObjectName::'
		['-servername']=$'ServerName::'
		['-gc']=$'Gc::'
		['-ssl']=$'Ssl::'
		['-sslcert']=$'SslCert::'
		['-sslkeyfile']=$'SslKeyFile::'
		['-sslkeypassword']=$'SslKeyPassword::'
		['-consoleoutputstyle']=$'ConsoleOutputStyle:list:Freeform;Raw;Table;List;Csv;Tsv;Json;TreeTable'
		['-outputheaders']=$'OutputHeaders::'
		['-loglevel']=$'LogLevel:list:Debug;Diagnostic;Verbose;Info;Warning;Error;Critical'
		['-consolelogformat']=$'ConsoleLogFormat:list:Text;TextWithTimestamp;Json'
		['-verbose']=$'Verbose::'
		['-diagnostic']=$'Diagnostic::'
		['-debuglog']=$'DebugLog::'
		['-humanreadable']=$'HumanReadable::'
		['-anonymous']=$'Anonymous::'
		['-username']=$'UserName::'
		['-userdomain']=$'UserDomain::'
		['-password']=$'Password::'
		['-ntlmhash']=$'NtlmHash::'
		['-aeskey']=$'AesKey::'
		['-deskey']=$'DesKey::'
		['-workstation']=$'Workstation::'
		['-tgt']=$'Tgt::'
		['-armorticket']=$'ArmorTicket::'
		['-tickets']=$'Tickets::'
		['-ticketcache']=$'TicketCache::'
		['-delegate']=$'Delegate::'
		['-delegateticket']=$'DelegateTicket::'
		['-ntlmversion']=$'NtlmVersion::'
		['-kdc']=$'Kdc::'
		['-keytab']=$'Keytab::'
		['-s4username']=$'S4UserName::'
		['-u2username']=$'U2UserName::'
		['-s4usercert']=$'S4UserCert::'
		['-s4proxyservice']=$'S4ProxyService::'
		['-spnoverride']=$'SpnOverride::'
		['-authproxy']=$'AuthProxy::'
		['-hostaddress']=$'HostAddress::'
		['-usetcp6only']=$'UseTcp6Only::'
		['-usetcp4only']=$'UseTcp4Only::'
		['-socks5']=$'Socks5::'
		['-usercert']=$'UserCert::'
		['-userkey']=$'UserKey::'
		['-userkeypassword']=$'UserKeyPassword::'
	)
	declare -a paramsByPos=(
		'ServerName'
		'ObjectName'
	)
	_comp_Titanis
}
complete -F _comp_Ldap_addou Ldap-addou

# Ldap adduser
_comp_Ldap_adduser () {
	declare -A params=(
		['-newpassword']=$'NewPassword::'
		['-logonname']=$'LogonName::'
		['-givenname']=$'GivenName::'
		['-surname']=$'Surname::'
		['-displayname']=$'DisplayName::'
		['-usercerts']=$'UserCerts::'
		['-memberof']=$'MemberOf::'
		['-attributes']=$'Attributes::'
		['-objectname']=$'ObjectName::'
		['-servername']=$'ServerName::'
		['-gc']=$'Gc::'
		['-ssl']=$'Ssl::'
		['-sslcert']=$'SslCert::'
		['-sslkeyfile']=$'SslKeyFile::'
		['-sslkeypassword']=$'SslKeyPassword::'
		['-consoleoutputstyle']=$'ConsoleOutputStyle:list:Freeform;Raw;Table;List;Csv;Tsv;Json;TreeTable'
		['-outputheaders']=$'OutputHeaders::'
		['-loglevel']=$'LogLevel:list:Debug;Diagnostic;Verbose;Info;Warning;Error;Critical'
		['-consolelogformat']=$'ConsoleLogFormat:list:Text;TextWithTimestamp;Json'
		['-verbose']=$'Verbose::'
		['-diagnostic']=$'Diagnostic::'
		['-debuglog']=$'DebugLog::'
		['-humanreadable']=$'HumanReadable::'
		['-anonymous']=$'Anonymous::'
		['-username']=$'UserName::'
		['-userdomain']=$'UserDomain::'
		['-password']=$'Password::'
		['-ntlmhash']=$'NtlmHash::'
		['-aeskey']=$'AesKey::'
		['-deskey']=$'DesKey::'
		['-workstation']=$'Workstation::'
		['-tgt']=$'Tgt::'
		['-armorticket']=$'ArmorTicket::'
		['-tickets']=$'Tickets::'
		['-ticketcache']=$'TicketCache::'
		['-delegate']=$'Delegate::'
		['-delegateticket']=$'DelegateTicket::'
		['-ntlmversion']=$'NtlmVersion::'
		['-kdc']=$'Kdc::'
		['-keytab']=$'Keytab::'
		['-s4username']=$'S4UserName::'
		['-u2username']=$'U2UserName::'
		['-s4usercert']=$'S4UserCert::'
		['-s4proxyservice']=$'S4ProxyService::'
		['-spnoverride']=$'SpnOverride::'
		['-authproxy']=$'AuthProxy::'
		['-hostaddress']=$'HostAddress::'
		['-usetcp6only']=$'UseTcp6Only::'
		['-usetcp4only']=$'UseTcp4Only::'
		['-socks5']=$'Socks5::'
		['-usercert']=$'UserCert::'
		['-userkey']=$'UserKey::'
		['-userkeypassword']=$'UserKeyPassword::'
	)
	declare -a paramsByPos=(
		'ServerName'
		'ObjectName'
	)
	_comp_Titanis
}
complete -F _comp_Ldap_adduser Ldap-adduser

# Ldap listsyntax
_comp_Ldap_listsyntax () {
	declare -A params=(
		['-consoleoutputstyle']=$'ConsoleOutputStyle:list:Freeform;Raw;Table;List;Csv;Tsv;Json;TreeTable'
		['-outputfields']=$'OutputFields:list:syntaxKey;memberName'
		['-outputheaders']=$'OutputHeaders::'
		['-loglevel']=$'LogLevel:list:Debug;Diagnostic;Verbose;Info;Warning;Error;Critical'
		['-consolelogformat']=$'ConsoleLogFormat:list:Text;TextWithTimestamp;Json'
		['-verbose']=$'Verbose::'
		['-diagnostic']=$'Diagnostic::'
		['-debuglog']=$'DebugLog::'
		['-humanreadable']=$'HumanReadable::'
	)
	declare -a paramsByPos=(
	)
	_comp_Titanis
}
complete -F _comp_Ldap_listsyntax Ldap-listsyntax

# Ldap lspart
_comp_Ldap_lspart () {
	declare -A params=(
		['-pagesize']=$'PageSize::'
		['-recordlimit']=$'RecordLimit::'
		['-followreferrals']=$'FollowReferrals::'
		['-servername']=$'ServerName::'
		['-gc']=$'Gc::'
		['-ssl']=$'Ssl::'
		['-sslcert']=$'SslCert::'
		['-sslkeyfile']=$'SslKeyFile::'
		['-sslkeypassword']=$'SslKeyPassword::'
		['-consoleoutputstyle']=$'ConsoleOutputStyle:list:Freeform;Raw;Table;List;Csv;Tsv;Json;TreeTable'
		['-outputfields']=$'OutputFields::'
		['-outputheaders']=$'OutputHeaders::'
		['-loglevel']=$'LogLevel:list:Debug;Diagnostic;Verbose;Info;Warning;Error;Critical'
		['-consolelogformat']=$'ConsoleLogFormat:list:Text;TextWithTimestamp;Json'
		['-verbose']=$'Verbose::'
		['-diagnostic']=$'Diagnostic::'
		['-debuglog']=$'DebugLog::'
		['-humanreadable']=$'HumanReadable::'
		['-anonymous']=$'Anonymous::'
		['-username']=$'UserName::'
		['-userdomain']=$'UserDomain::'
		['-password']=$'Password::'
		['-ntlmhash']=$'NtlmHash::'
		['-aeskey']=$'AesKey::'
		['-deskey']=$'DesKey::'
		['-workstation']=$'Workstation::'
		['-tgt']=$'Tgt::'
		['-armorticket']=$'ArmorTicket::'
		['-tickets']=$'Tickets::'
		['-ticketcache']=$'TicketCache::'
		['-delegate']=$'Delegate::'
		['-delegateticket']=$'DelegateTicket::'
		['-ntlmversion']=$'NtlmVersion::'
		['-kdc']=$'Kdc::'
		['-keytab']=$'Keytab::'
		['-s4username']=$'S4UserName::'
		['-u2username']=$'U2UserName::'
		['-s4usercert']=$'S4UserCert::'
		['-s4proxyservice']=$'S4ProxyService::'
		['-spnoverride']=$'SpnOverride::'
		['-authproxy']=$'AuthProxy::'
		['-hostaddress']=$'HostAddress::'
		['-usetcp6only']=$'UseTcp6Only::'
		['-usetcp4only']=$'UseTcp4Only::'
		['-socks5']=$'Socks5::'
		['-usercert']=$'UserCert::'
		['-userkey']=$'UserKey::'
		['-userkeypassword']=$'UserKeyPassword::'
	)
	declare -a paramsByPos=(
		'ServerName'
	)
	_comp_Titanis
}
complete -F _comp_Ldap_lspart Ldap-lspart

# Ldap mod
_comp_Ldap_mod () {
	declare -A params=(
		['-changes']=$'Changes::'
		['-allowonbehalfof']=$'AllowOnBehalfOf::'
		['-objectname']=$'ObjectName::'
		['-servername']=$'ServerName::'
		['-gc']=$'Gc::'
		['-ssl']=$'Ssl::'
		['-sslcert']=$'SslCert::'
		['-sslkeyfile']=$'SslKeyFile::'
		['-sslkeypassword']=$'SslKeyPassword::'
		['-consoleoutputstyle']=$'ConsoleOutputStyle:list:Freeform;Raw;Table;List;Csv;Tsv;Json;TreeTable'
		['-outputheaders']=$'OutputHeaders::'
		['-loglevel']=$'LogLevel:list:Debug;Diagnostic;Verbose;Info;Warning;Error;Critical'
		['-consolelogformat']=$'ConsoleLogFormat:list:Text;TextWithTimestamp;Json'
		['-verbose']=$'Verbose::'
		['-diagnostic']=$'Diagnostic::'
		['-debuglog']=$'DebugLog::'
		['-humanreadable']=$'HumanReadable::'
		['-anonymous']=$'Anonymous::'
		['-username']=$'UserName::'
		['-userdomain']=$'UserDomain::'
		['-password']=$'Password::'
		['-ntlmhash']=$'NtlmHash::'
		['-aeskey']=$'AesKey::'
		['-deskey']=$'DesKey::'
		['-workstation']=$'Workstation::'
		['-tgt']=$'Tgt::'
		['-armorticket']=$'ArmorTicket::'
		['-tickets']=$'Tickets::'
		['-ticketcache']=$'TicketCache::'
		['-delegate']=$'Delegate::'
		['-delegateticket']=$'DelegateTicket::'
		['-ntlmversion']=$'NtlmVersion::'
		['-kdc']=$'Kdc::'
		['-keytab']=$'Keytab::'
		['-s4username']=$'S4UserName::'
		['-u2username']=$'U2UserName::'
		['-s4usercert']=$'S4UserCert::'
		['-s4proxyservice']=$'S4ProxyService::'
		['-spnoverride']=$'SpnOverride::'
		['-authproxy']=$'AuthProxy::'
		['-hostaddress']=$'HostAddress::'
		['-usetcp6only']=$'UseTcp6Only::'
		['-usetcp4only']=$'UseTcp4Only::'
		['-socks5']=$'Socks5::'
		['-usercert']=$'UserCert::'
		['-userkey']=$'UserKey::'
		['-userkeypassword']=$'UserKeyPassword::'
	)
	declare -a paramsByPos=(
		'ServerName'
		'ObjectName'
		'Changes'
	)
	_comp_Titanis
}
complete -F _comp_Ldap_mod Ldap-mod

# Ldap moduser
_comp_Ldap_moduser () {
	declare -A params=(
		['-oldpassword']=$'OldPassword::'
		['-newpassword']=$'NewPassword::'
		['-changes']=$'Changes::'
		['-allowonbehalfof']=$'AllowOnBehalfOf::'
		['-objectname']=$'ObjectName::'
		['-servername']=$'ServerName::'
		['-gc']=$'Gc::'
		['-ssl']=$'Ssl::'
		['-sslcert']=$'SslCert::'
		['-sslkeyfile']=$'SslKeyFile::'
		['-sslkeypassword']=$'SslKeyPassword::'
		['-consoleoutputstyle']=$'ConsoleOutputStyle:list:Freeform;Raw;Table;List;Csv;Tsv;Json;TreeTable'
		['-outputheaders']=$'OutputHeaders::'
		['-loglevel']=$'LogLevel:list:Debug;Diagnostic;Verbose;Info;Warning;Error;Critical'
		['-consolelogformat']=$'ConsoleLogFormat:list:Text;TextWithTimestamp;Json'
		['-verbose']=$'Verbose::'
		['-diagnostic']=$'Diagnostic::'
		['-debuglog']=$'DebugLog::'
		['-humanreadable']=$'HumanReadable::'
		['-anonymous']=$'Anonymous::'
		['-username']=$'UserName::'
		['-userdomain']=$'UserDomain::'
		['-password']=$'Password::'
		['-ntlmhash']=$'NtlmHash::'
		['-aeskey']=$'AesKey::'
		['-deskey']=$'DesKey::'
		['-workstation']=$'Workstation::'
		['-tgt']=$'Tgt::'
		['-armorticket']=$'ArmorTicket::'
		['-tickets']=$'Tickets::'
		['-ticketcache']=$'TicketCache::'
		['-delegate']=$'Delegate::'
		['-delegateticket']=$'DelegateTicket::'
		['-ntlmversion']=$'NtlmVersion::'
		['-kdc']=$'Kdc::'
		['-keytab']=$'Keytab::'
		['-s4username']=$'S4UserName::'
		['-u2username']=$'U2UserName::'
		['-s4usercert']=$'S4UserCert::'
		['-s4proxyservice']=$'S4ProxyService::'
		['-spnoverride']=$'SpnOverride::'
		['-authproxy']=$'AuthProxy::'
		['-hostaddress']=$'HostAddress::'
		['-usetcp6only']=$'UseTcp6Only::'
		['-usetcp4only']=$'UseTcp4Only::'
		['-socks5']=$'Socks5::'
		['-usercert']=$'UserCert::'
		['-userkey']=$'UserKey::'
		['-userkeypassword']=$'UserKeyPassword::'
	)
	declare -a paramsByPos=(
		'ServerName'
		'ObjectName'
		'Changes'
	)
	_comp_Titanis
}
complete -F _comp_Ldap_moduser Ldap-moduser

# Ldap mountfs
_comp_Ldap_mountfs () {
	declare -A params=(
		['-searchbase']=$'SearchBase::'
		['-servername']=$'ServerName::'
		['-gc']=$'Gc::'
		['-ssl']=$'Ssl::'
		['-sslcert']=$'SslCert::'
		['-sslkeyfile']=$'SslKeyFile::'
		['-sslkeypassword']=$'SslKeyPassword::'
		['-consoleoutputstyle']=$'ConsoleOutputStyle:list:Freeform;Raw;Table;List;Csv;Tsv;Json;TreeTable'
		['-outputheaders']=$'OutputHeaders::'
		['-loglevel']=$'LogLevel:list:Debug;Diagnostic;Verbose;Info;Warning;Error;Critical'
		['-consolelogformat']=$'ConsoleLogFormat:list:Text;TextWithTimestamp;Json'
		['-verbose']=$'Verbose::'
		['-diagnostic']=$'Diagnostic::'
		['-debuglog']=$'DebugLog::'
		['-humanreadable']=$'HumanReadable::'
		['-mountpoint']=$'Mountpoint::'
		['-uid']=$'Uid::'
		['-gid']=$'Gid::'
		['-readwrite']=$'ReadWrite::'
		['-anonymous']=$'Anonymous::'
		['-username']=$'UserName::'
		['-userdomain']=$'UserDomain::'
		['-password']=$'Password::'
		['-ntlmhash']=$'NtlmHash::'
		['-aeskey']=$'AesKey::'
		['-deskey']=$'DesKey::'
		['-workstation']=$'Workstation::'
		['-tgt']=$'Tgt::'
		['-armorticket']=$'ArmorTicket::'
		['-tickets']=$'Tickets::'
		['-ticketcache']=$'TicketCache::'
		['-delegate']=$'Delegate::'
		['-delegateticket']=$'DelegateTicket::'
		['-ntlmversion']=$'NtlmVersion::'
		['-kdc']=$'Kdc::'
		['-keytab']=$'Keytab::'
		['-s4username']=$'S4UserName::'
		['-u2username']=$'U2UserName::'
		['-s4usercert']=$'S4UserCert::'
		['-s4proxyservice']=$'S4ProxyService::'
		['-spnoverride']=$'SpnOverride::'
		['-authproxy']=$'AuthProxy::'
		['-hostaddress']=$'HostAddress::'
		['-usetcp6only']=$'UseTcp6Only::'
		['-usetcp4only']=$'UseTcp4Only::'
		['-socks5']=$'Socks5::'
		['-usercert']=$'UserCert::'
		['-userkey']=$'UserKey::'
		['-userkeypassword']=$'UserKeyPassword::'
	)
	declare -a paramsByPos=(
		'ServerName'
		'Mountpoint'
	)
	_comp_Titanis
}
complete -F _comp_Ldap_mountfs Ldap-mountfs

# Ldap namedbits
_comp_Ldap_namedbits () {
	declare -A params=(
		['-attribute']=$'Attribute::'
		['-consoleoutputstyle']=$'ConsoleOutputStyle:list:Freeform;Raw;Table;List;Csv;Tsv;Json;TreeTable'
		['-outputfields']=$'OutputFields:list:Attribute;Name;Value;HexValue'
		['-outputheaders']=$'OutputHeaders::'
		['-loglevel']=$'LogLevel:list:Debug;Diagnostic;Verbose;Info;Warning;Error;Critical'
		['-consolelogformat']=$'ConsoleLogFormat:list:Text;TextWithTimestamp;Json'
		['-verbose']=$'Verbose::'
		['-diagnostic']=$'Diagnostic::'
		['-debuglog']=$'DebugLog::'
		['-humanreadable']=$'HumanReadable::'
	)
	declare -a paramsByPos=(
		'Attribute'
	)
	_comp_Titanis
}
complete -F _comp_Ldap_namedbits Ldap-namedbits

# Ldap query
_comp_Ldap_query () {
	declare -A params=(
		['-filter']=$'Filter::'
		['-searchbase']=$'SearchBase::'
		['-scope']=$'Scope:list:BaseObject;Base;SingleLevel;WholeSubtree;Subtree'
		['-includedeleted']=$'IncludeDeleted::'
		['-includerecycled']=$'IncludeRecycled::'
		['-includedeletedlinks']=$'IncludeDeletedLinks::'
		['-dirsync']=$'DirSync::'
		['-extendeddn']=$'ExtendedDN::'
		['-linkttl']=$'LinkTtl::'
		['-pagesize']=$'PageSize::'
		['-recordlimit']=$'RecordLimit::'
		['-followreferrals']=$'FollowReferrals::'
		['-servername']=$'ServerName::'
		['-gc']=$'Gc::'
		['-ssl']=$'Ssl::'
		['-sslcert']=$'SslCert::'
		['-sslkeyfile']=$'SslKeyFile::'
		['-sslkeypassword']=$'SslKeyPassword::'
		['-consoleoutputstyle']=$'ConsoleOutputStyle:list:Freeform;Raw;Table;List;Csv;Tsv;Json;TreeTable'
		['-outputheaders']=$'OutputHeaders::'
		['-loglevel']=$'LogLevel:list:Debug;Diagnostic;Verbose;Info;Warning;Error;Critical'
		['-consolelogformat']=$'ConsoleLogFormat:list:Text;TextWithTimestamp;Json'
		['-verbose']=$'Verbose::'
		['-diagnostic']=$'Diagnostic::'
		['-debuglog']=$'DebugLog::'
		['-humanreadable']=$'HumanReadable::'
		['-anonymous']=$'Anonymous::'
		['-username']=$'UserName::'
		['-userdomain']=$'UserDomain::'
		['-password']=$'Password::'
		['-ntlmhash']=$'NtlmHash::'
		['-aeskey']=$'AesKey::'
		['-deskey']=$'DesKey::'
		['-workstation']=$'Workstation::'
		['-tgt']=$'Tgt::'
		['-armorticket']=$'ArmorTicket::'
		['-tickets']=$'Tickets::'
		['-ticketcache']=$'TicketCache::'
		['-delegate']=$'Delegate::'
		['-delegateticket']=$'DelegateTicket::'
		['-ntlmversion']=$'NtlmVersion::'
		['-kdc']=$'Kdc::'
		['-keytab']=$'Keytab::'
		['-s4username']=$'S4UserName::'
		['-u2username']=$'U2UserName::'
		['-s4usercert']=$'S4UserCert::'
		['-s4proxyservice']=$'S4ProxyService::'
		['-spnoverride']=$'SpnOverride::'
		['-authproxy']=$'AuthProxy::'
		['-hostaddress']=$'HostAddress::'
		['-usetcp6only']=$'UseTcp6Only::'
		['-usetcp4only']=$'UseTcp4Only::'
		['-socks5']=$'Socks5::'
		['-usercert']=$'UserCert::'
		['-userkey']=$'UserKey::'
		['-userkeypassword']=$'UserKeyPassword::'
	)
	declare -a paramsByPos=(
		'ServerName'
		'Filter'
	)
	_comp_Titanis
}
complete -F _comp_Ldap_query Ldap-query

# Ldap rm
_comp_Ldap_rm () {
	declare -A params=(
		['-objectname']=$'ObjectName::'
		['-servername']=$'ServerName::'
		['-gc']=$'Gc::'
		['-ssl']=$'Ssl::'
		['-sslcert']=$'SslCert::'
		['-sslkeyfile']=$'SslKeyFile::'
		['-sslkeypassword']=$'SslKeyPassword::'
		['-consoleoutputstyle']=$'ConsoleOutputStyle:list:Freeform;Raw;Table;List;Csv;Tsv;Json;TreeTable'
		['-outputheaders']=$'OutputHeaders::'
		['-loglevel']=$'LogLevel:list:Debug;Diagnostic;Verbose;Info;Warning;Error;Critical'
		['-consolelogformat']=$'ConsoleLogFormat:list:Text;TextWithTimestamp;Json'
		['-verbose']=$'Verbose::'
		['-diagnostic']=$'Diagnostic::'
		['-debuglog']=$'DebugLog::'
		['-humanreadable']=$'HumanReadable::'
		['-anonymous']=$'Anonymous::'
		['-username']=$'UserName::'
		['-userdomain']=$'UserDomain::'
		['-password']=$'Password::'
		['-ntlmhash']=$'NtlmHash::'
		['-aeskey']=$'AesKey::'
		['-deskey']=$'DesKey::'
		['-workstation']=$'Workstation::'
		['-tgt']=$'Tgt::'
		['-armorticket']=$'ArmorTicket::'
		['-tickets']=$'Tickets::'
		['-ticketcache']=$'TicketCache::'
		['-delegate']=$'Delegate::'
		['-delegateticket']=$'DelegateTicket::'
		['-ntlmversion']=$'NtlmVersion::'
		['-kdc']=$'Kdc::'
		['-keytab']=$'Keytab::'
		['-s4username']=$'S4UserName::'
		['-u2username']=$'U2UserName::'
		['-s4usercert']=$'S4UserCert::'
		['-s4proxyservice']=$'S4ProxyService::'
		['-spnoverride']=$'SpnOverride::'
		['-authproxy']=$'AuthProxy::'
		['-hostaddress']=$'HostAddress::'
		['-usetcp6only']=$'UseTcp6Only::'
		['-usetcp4only']=$'UseTcp4Only::'
		['-socks5']=$'Socks5::'
		['-usercert']=$'UserCert::'
		['-userkey']=$'UserKey::'
		['-userkeypassword']=$'UserKeyPassword::'
	)
	declare -a paramsByPos=(
		'ServerName'
		'ObjectName'
	)
	_comp_Titanis
}
complete -F _comp_Ldap_rm Ldap-rm

# Ldap schema
_comp_Ldap_schema () {
	declare -A params=(
		['-servername']=$'ServerName::'
		['-gc']=$'Gc::'
		['-ssl']=$'Ssl::'
		['-sslcert']=$'SslCert::'
		['-sslkeyfile']=$'SslKeyFile::'
		['-sslkeypassword']=$'SslKeyPassword::'
		['-consoleoutputstyle']=$'ConsoleOutputStyle:list:Freeform;Raw;Table;List;Csv;Tsv;Json;TreeTable'
		['-outputfields']=$'OutputFields::'
		['-outputheaders']=$'OutputHeaders::'
		['-loglevel']=$'LogLevel:list:Debug;Diagnostic;Verbose;Info;Warning;Error;Critical'
		['-consolelogformat']=$'ConsoleLogFormat:list:Text;TextWithTimestamp;Json'
		['-verbose']=$'Verbose::'
		['-diagnostic']=$'Diagnostic::'
		['-debuglog']=$'DebugLog::'
		['-humanreadable']=$'HumanReadable::'
		['-anonymous']=$'Anonymous::'
		['-username']=$'UserName::'
		['-userdomain']=$'UserDomain::'
		['-password']=$'Password::'
		['-ntlmhash']=$'NtlmHash::'
		['-aeskey']=$'AesKey::'
		['-deskey']=$'DesKey::'
		['-workstation']=$'Workstation::'
		['-tgt']=$'Tgt::'
		['-armorticket']=$'ArmorTicket::'
		['-tickets']=$'Tickets::'
		['-ticketcache']=$'TicketCache::'
		['-delegate']=$'Delegate::'
		['-delegateticket']=$'DelegateTicket::'
		['-ntlmversion']=$'NtlmVersion::'
		['-kdc']=$'Kdc::'
		['-keytab']=$'Keytab::'
		['-s4username']=$'S4UserName::'
		['-u2username']=$'U2UserName::'
		['-s4usercert']=$'S4UserCert::'
		['-s4proxyservice']=$'S4ProxyService::'
		['-spnoverride']=$'SpnOverride::'
		['-authproxy']=$'AuthProxy::'
		['-hostaddress']=$'HostAddress::'
		['-usetcp6only']=$'UseTcp6Only::'
		['-usetcp4only']=$'UseTcp4Only::'
		['-socks5']=$'Socks5::'
		['-usercert']=$'UserCert::'
		['-userkey']=$'UserKey::'
		['-userkeypassword']=$'UserKeyPassword::'
	)
	declare -a paramsByPos=(
		'ServerName'
	)
	_comp_Titanis
}
complete -F _comp_Ldap_schema Ldap-schema

# Ldap search
_comp_Ldap_search () {
	declare -A params=(
		['-searchname']=$'SearchName::'
		['-searchbase']=$'SearchBase::'
		['-scope']=$'Scope:list:BaseObject;Base;SingleLevel;WholeSubtree;Subtree'
		['-includedeleted']=$'IncludeDeleted::'
		['-includerecycled']=$'IncludeRecycled::'
		['-includedeletedlinks']=$'IncludeDeletedLinks::'
		['-dirsync']=$'DirSync::'
		['-extendeddn']=$'ExtendedDN::'
		['-linkttl']=$'LinkTtl::'
		['-pagesize']=$'PageSize::'
		['-recordlimit']=$'RecordLimit::'
		['-followreferrals']=$'FollowReferrals::'
		['-servername']=$'ServerName::'
		['-gc']=$'Gc::'
		['-ssl']=$'Ssl::'
		['-sslcert']=$'SslCert::'
		['-sslkeyfile']=$'SslKeyFile::'
		['-sslkeypassword']=$'SslKeyPassword::'
		['-consoleoutputstyle']=$'ConsoleOutputStyle:list:Freeform;Raw;Table;List;Csv;Tsv;Json;TreeTable'
		['-outputheaders']=$'OutputHeaders::'
		['-loglevel']=$'LogLevel:list:Debug;Diagnostic;Verbose;Info;Warning;Error;Critical'
		['-consolelogformat']=$'ConsoleLogFormat:list:Text;TextWithTimestamp;Json'
		['-verbose']=$'Verbose::'
		['-diagnostic']=$'Diagnostic::'
		['-debuglog']=$'DebugLog::'
		['-humanreadable']=$'HumanReadable::'
		['-anonymous']=$'Anonymous::'
		['-username']=$'UserName::'
		['-userdomain']=$'UserDomain::'
		['-password']=$'Password::'
		['-ntlmhash']=$'NtlmHash::'
		['-aeskey']=$'AesKey::'
		['-deskey']=$'DesKey::'
		['-workstation']=$'Workstation::'
		['-tgt']=$'Tgt::'
		['-armorticket']=$'ArmorTicket::'
		['-tickets']=$'Tickets::'
		['-ticketcache']=$'TicketCache::'
		['-delegate']=$'Delegate::'
		['-delegateticket']=$'DelegateTicket::'
		['-ntlmversion']=$'NtlmVersion::'
		['-kdc']=$'Kdc::'
		['-keytab']=$'Keytab::'
		['-s4username']=$'S4UserName::'
		['-u2username']=$'U2UserName::'
		['-s4usercert']=$'S4UserCert::'
		['-s4proxyservice']=$'S4ProxyService::'
		['-spnoverride']=$'SpnOverride::'
		['-authproxy']=$'AuthProxy::'
		['-hostaddress']=$'HostAddress::'
		['-usetcp6only']=$'UseTcp6Only::'
		['-usetcp4only']=$'UseTcp4Only::'
		['-socks5']=$'Socks5::'
		['-usercert']=$'UserCert::'
		['-userkey']=$'UserKey::'
		['-userkeypassword']=$'UserKeyPassword::'
	)
	declare -a paramsByPos=(
		'ServerName'
		'SearchName'
	)
	_comp_Titanis
}
complete -F _comp_Ldap_search Ldap-search

# Ldap timestamp
_comp_Ldap_timestamp () {
	declare -A params=(
		['-timestampordate']=$'TimestampOrDate::'
		['-consoleoutputstyle']=$'ConsoleOutputStyle:list:Freeform;Raw;Table;List;Csv;Tsv;Json;TreeTable'
		['-outputheaders']=$'OutputHeaders::'
		['-loglevel']=$'LogLevel:list:Debug;Diagnostic;Verbose;Info;Warning;Error;Critical'
		['-consolelogformat']=$'ConsoleLogFormat:list:Text;TextWithTimestamp;Json'
		['-verbose']=$'Verbose::'
		['-diagnostic']=$'Diagnostic::'
		['-debuglog']=$'DebugLog::'
		['-humanreadable']=$'HumanReadable::'
	)
	declare -a paramsByPos=(
		'TimestampOrDate'
	)
	_comp_Titanis
}
complete -F _comp_Ldap_timestamp Ldap-timestamp

# Ldap watch
_comp_Ldap_watch () {
	declare -A params=(
		['-searchbase']=$'SearchBase::'
		['-scope']=$'Scope:list:BaseObject;Base;SingleLevel;WholeSubtree;Subtree'
		['-includedeleted']=$'IncludeDeleted::'
		['-includerecycled']=$'IncludeRecycled::'
		['-includedeletedlinks']=$'IncludeDeletedLinks::'
		['-dirsync']=$'DirSync::'
		['-extendeddn']=$'ExtendedDN::'
		['-linkttl']=$'LinkTtl::'
		['-pagesize']=$'PageSize::'
		['-recordlimit']=$'RecordLimit::'
		['-followreferrals']=$'FollowReferrals::'
		['-servername']=$'ServerName::'
		['-gc']=$'Gc::'
		['-ssl']=$'Ssl::'
		['-sslcert']=$'SslCert::'
		['-sslkeyfile']=$'SslKeyFile::'
		['-sslkeypassword']=$'SslKeyPassword::'
		['-consoleoutputstyle']=$'ConsoleOutputStyle:list:Freeform;Raw;Table;List;Csv;Tsv;Json;TreeTable'
		['-outputfields']=$'OutputFields::'
		['-outputheaders']=$'OutputHeaders::'
		['-loglevel']=$'LogLevel:list:Debug;Diagnostic;Verbose;Info;Warning;Error;Critical'
		['-consolelogformat']=$'ConsoleLogFormat:list:Text;TextWithTimestamp;Json'
		['-verbose']=$'Verbose::'
		['-diagnostic']=$'Diagnostic::'
		['-debuglog']=$'DebugLog::'
		['-humanreadable']=$'HumanReadable::'
		['-anonymous']=$'Anonymous::'
		['-username']=$'UserName::'
		['-userdomain']=$'UserDomain::'
		['-password']=$'Password::'
		['-ntlmhash']=$'NtlmHash::'
		['-aeskey']=$'AesKey::'
		['-deskey']=$'DesKey::'
		['-workstation']=$'Workstation::'
		['-tgt']=$'Tgt::'
		['-armorticket']=$'ArmorTicket::'
		['-tickets']=$'Tickets::'
		['-ticketcache']=$'TicketCache::'
		['-delegate']=$'Delegate::'
		['-delegateticket']=$'DelegateTicket::'
		['-ntlmversion']=$'NtlmVersion::'
		['-kdc']=$'Kdc::'
		['-keytab']=$'Keytab::'
		['-s4username']=$'S4UserName::'
		['-u2username']=$'U2UserName::'
		['-s4usercert']=$'S4UserCert::'
		['-s4proxyservice']=$'S4ProxyService::'
		['-spnoverride']=$'SpnOverride::'
		['-authproxy']=$'AuthProxy::'
		['-hostaddress']=$'HostAddress::'
		['-usetcp6only']=$'UseTcp6Only::'
		['-usetcp4only']=$'UseTcp4Only::'
		['-socks5']=$'Socks5::'
		['-usercert']=$'UserCert::'
		['-userkey']=$'UserKey::'
		['-userkeypassword']=$'UserKeyPassword::'
	)
	declare -a paramsByPos=(
		'ServerName'
	)
	_comp_Titanis
}
complete -F _comp_Ldap_watch Ldap-watch

# Ldap whoami
_comp_Ldap_whoami () {
	declare -A params=(
		['-servername']=$'ServerName::'
		['-gc']=$'Gc::'
		['-ssl']=$'Ssl::'
		['-sslcert']=$'SslCert::'
		['-sslkeyfile']=$'SslKeyFile::'
		['-sslkeypassword']=$'SslKeyPassword::'
		['-consoleoutputstyle']=$'ConsoleOutputStyle:list:Freeform;Raw;Table;List;Csv;Tsv;Json;TreeTable'
		['-outputfields']=$'OutputFields:list:SaslString;PrincipalName;Kind'
		['-outputheaders']=$'OutputHeaders::'
		['-loglevel']=$'LogLevel:list:Debug;Diagnostic;Verbose;Info;Warning;Error;Critical'
		['-consolelogformat']=$'ConsoleLogFormat:list:Text;TextWithTimestamp;Json'
		['-verbose']=$'Verbose::'
		['-diagnostic']=$'Diagnostic::'
		['-debuglog']=$'DebugLog::'
		['-humanreadable']=$'HumanReadable::'
		['-anonymous']=$'Anonymous::'
		['-username']=$'UserName::'
		['-userdomain']=$'UserDomain::'
		['-password']=$'Password::'
		['-ntlmhash']=$'NtlmHash::'
		['-aeskey']=$'AesKey::'
		['-deskey']=$'DesKey::'
		['-workstation']=$'Workstation::'
		['-tgt']=$'Tgt::'
		['-armorticket']=$'ArmorTicket::'
		['-tickets']=$'Tickets::'
		['-ticketcache']=$'TicketCache::'
		['-delegate']=$'Delegate::'
		['-delegateticket']=$'DelegateTicket::'
		['-ntlmversion']=$'NtlmVersion::'
		['-kdc']=$'Kdc::'
		['-keytab']=$'Keytab::'
		['-s4username']=$'S4UserName::'
		['-u2username']=$'U2UserName::'
		['-s4usercert']=$'S4UserCert::'
		['-s4proxyservice']=$'S4ProxyService::'
		['-spnoverride']=$'SpnOverride::'
		['-authproxy']=$'AuthProxy::'
		['-hostaddress']=$'HostAddress::'
		['-usetcp6only']=$'UseTcp6Only::'
		['-usetcp4only']=$'UseTcp4Only::'
		['-socks5']=$'Socks5::'
		['-usercert']=$'UserCert::'
		['-userkey']=$'UserKey::'
		['-userkeypassword']=$'UserKeyPassword::'
	)
	declare -a paramsByPos=(
		'ServerName'
	)
	_comp_Titanis
}
complete -F _comp_Ldap_whoami Ldap-whoami
