<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
		<RootNamespace>Titanis.Crypto</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Titanis.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\base\Titanis.Core\Titanis.Core.csproj" />
  </ItemGroup>

</Project>
