//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Titanis.Cli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Titanis.Cli.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing parameter &apos;{0}&apos;, value &apos;{1}&apos;: {2}.
        /// </summary>
        internal static string Cli_ArgFormatError {
            get {
                return ResourceManager.GetString("Cli_ArgFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are more than one parameters with the name &apos;{0}&apos;..
        /// </summary>
        internal static string Cli_DuplicateParamName {
            get {
                return ResourceManager.GetString("Cli_DuplicateParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is mandatory, but no value was specified..
        /// </summary>
        internal static string Cli_MandatoryArgMissing_ParamName {
            get {
                return ResourceManager.GetString("Cli_MandatoryArgMissing_ParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value specified for parameter &apos;{0}&apos;..
        /// </summary>
        internal static string Cli_MissingParamValue {
            get {
                return ResourceManager.GetString("Cli_MissingParamValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description not provided.
        /// </summary>
        internal static string Cli_NoDescriptionProvided {
            get {
                return ResourceManager.GetString("Cli_NoDescriptionProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commandType does not specify a type derived from Command..
        /// </summary>
        internal static string Cli_NonCommandType {
            get {
                return ResourceManager.GetString("Cli_NonCommandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subcommand provided..
        /// </summary>
        internal static string Cli_NoSubcommandProvided {
            get {
                return ResourceManager.GetString("Cli_NoSubcommandProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter does not support parsing..
        /// </summary>
        internal static string Cli_ParamParseNotSupported {
            get {
                return ResourceManager.GetString("Cli_ParamParseNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many arguments specified..
        /// </summary>
        internal static string Cli_TooManyArguments {
            get {
                return ResourceManager.GetString("Cli_TooManyArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is not recognized..
        /// </summary>
        internal static string Cli_UnrecognizedParam {
            get {
                return ResourceManager.GetString("Cli_UnrecognizedParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not supported as a parameter type..
        /// </summary>
        internal static string Cli_UnsupportedParamType {
            get {
                return ResourceManager.GetString("Cli_UnsupportedParamType", resourceCulture);
            }
        }
    }
}
