//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Titanis.Smb2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Titanis.Smb2.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For &gt;=SMB 3.1.1, the preauthentication salt must be &gt; 0..
        /// </summary>
        internal static string Smb2_BadPreauthSaltLength {
            get {
                return ResourceManager.GetString("Smb2_BadPreauthSaltLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream does not support both reading and writing..
        /// </summary>
        internal static string Smb2_BadStream {
            get {
                return ResourceManager.GetString("Smb2_BadStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server returned a response that didn&apos;t match the command..
        /// </summary>
        internal static string Smb2_CommandResponseMismatch {
            get {
                return ResourceManager.GetString("Smb2_CommandResponseMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An SMB2 error has occurred (error code = 0x{0:X}).
        /// </summary>
        internal static string Smb2_GenericErrorFormat {
            get {
                return ResourceManager.GetString("Smb2_GenericErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An SMB2 error has occurred (error code = {0:G} [0x{0:X}]).
        /// </summary>
        internal static string Smb2_GenericNamedErrorFormat {
            get {
                return ResourceManager.GetString("Smb2_GenericNamedErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid UNC path.  A UNC path must start with \\ followed by a server name or IP address, optionally followed by a share name and path..
        /// </summary>
        internal static string Smb2_InvalidUncPath {
            get {
                return ResourceManager.GetString("Smb2_InvalidUncPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Smb2Client is not configured to support any SMB2 dialects.  Set the SupportedDialects property..
        /// </summary>
        internal static string Smb2_NoDialects {
            get {
                return ResourceManager.GetString("Smb2_NoDialects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Smb2Client is not configured to support any hash algorithms, which is required for SMB 3.1.1 and above..
        /// </summary>
        internal static string Smb2_NoHashAlgs {
            get {
                return ResourceManager.GetString("Smb2_NoHashAlgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SMB2 server did not return a valid negotiate response..
        /// </summary>
        internal static string Smb2_NoNegotiateResponse {
            get {
                return ResourceManager.GetString("Smb2_NoNegotiateResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SMB2 server did not return a valid session setup response..
        /// </summary>
        internal static string Smb2_NoSessionResponse {
            get {
                return ResourceManager.GetString("Smb2_NoSessionResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The symlink depth was exceeded..
        /// </summary>
        internal static string Smb2_RecursiveSymlink {
            get {
                return ResourceManager.GetString("Smb2_RecursiveSymlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When negotiating SMB 3.1.1, signing must be enabled..
        /// </summary>
        internal static string Smb2_Smb311VersionSigningRequired {
            get {
                return ResourceManager.GetString("Smb2_Smb311VersionSigningRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The receive buffer size should be at least 1024..
        /// </summary>
        internal static string Smb2Channel_InsufficientReceiveBuffer {
            get {
                return ResourceManager.GetString("Smb2Channel_InsufficientReceiveBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SOCKADDR structure cannot be converted to an IP endpoint..
        /// </summary>
        internal static string Sockaddr_InvalidFamily {
            get {
                return ResourceManager.GetString("Sockaddr_InvalidFamily", resourceCulture);
            }
        }
    }
}
