<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Titanis.Msrpc.Msrrp.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\base\Titanis.Cli.CommonParameters\Titanis.Cli.CommonParameters.csproj" />
    <ProjectReference Include="..\..\..\src\base\Titanis.Cli.DceRpc\Titanis.Cli.DceRpc.csproj" />
    <ProjectReference Include="..\..\..\src\base\Titanis.Cli.Registry\Titanis.Cli.Registry.csproj" />
    <ProjectReference Include="..\..\..\src\base\Titanis.Cli\Titanis.Cli.csproj" />
    <ProjectReference Include="..\..\..\src\base\Titanis.Core\Titanis.Core.csproj" />
    <ProjectReference Include="..\..\..\src\base\Titanis.IO\Titanis.IO.csproj" />
    <ProjectReference Include="..\..\..\src\base\Titanis.Winterop.Lsa\Titanis.Winterop.Lsa.csproj" />
    <ProjectReference Include="..\..\..\src\base\Titanis.Winterop.Sam\Titanis.Winterop.Sam.csproj" />
    <ProjectReference Include="..\..\..\src\net\msrpc\Titanis.Msrpc.Msrrp\Titanis.Msrpc.Msrrp.csproj" />
    <ProjectReference Include="..\..\..\src\net\msrpc\Titanis.Msrpc.Mssrvs\Titanis.Msrpc.Mssrvs.csproj" />
    <ProjectReference Include="..\..\..\src\net\Titanis.Smb2\Titanis.Smb2.csproj" />
  </ItemGroup>

</Project>
