<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\crypto\Titanis.Crypto.Des\Titanis.Crypto.Des.csproj" />
    <ProjectReference Include="..\Titanis.IO\Titanis.IO.csproj" />
    <ProjectReference Include="..\Titanis.Winterop.Registry\Titanis.Winterop.Registry.csproj" />
    <ProjectReference Include="..\Titanis.Winterop.Security\Titanis.Winterop.Security.csproj" />
    <ProjectReference Include="..\..\build\Titanis.SourceGeneration.PduStruct\Titanis.SourceGeneration.PduStruct.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>

</Project>
