using KerberosV5Spec2;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Net;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Titanis.Asn1;
using Titanis.Asn1.Serialization;

namespace Titanis.Security.Kerberos
{
	public sealed class KerberosClientCred
	{
		public KerberosClientCred(TicketInfo ticket)
		{
			ArgumentNullException.ThrowIfNull(ticket);
			Ticket = ticket;
		}
		public KerberosClientCred(TicketInfo tgt, UserPrincipalName u2UserName)
		{
			ArgumentNullException.ThrowIfNull(u2UserName);
			this.Tgt = tgt;
			U2UserName = u2UserName;
		}

		public TicketInfo? Ticket { get; private set; }
		public TicketInfo Tgt { get; }
		public UserPrincipalName? U2UserName { get; }
		public IReadOnlyList<TicketInfo>? ForwardedTickets { get; set; }

		public static implicit operator KerberosClientCred(TicketInfo ticket) => new KerberosClientCred(ticket);
	}

	/// <summary>
	/// Implements a Kerberos authentication client.
	/// </summary>
	/// <seealso cref="MskileClientContext"/>
	/// <seealso cref="KerberosClientContext"/>
	public abstract class KerberosClientContextBase : AuthClientContext
	{
		public KerberosClientContextBase(
			KerberosCredential credential,
			KerberosClient client,
			SecurityPrincipalName targetSpn,
			KerberosClientCred clientCred,
			IKerberosCallback? callback = null
			)
		{
			if (credential is null)
				throw new ArgumentNullException(nameof(credential));
			if (client is null)
				throw new ArgumentNullException(nameof(client));

			this.Credential = credential;
			this._client = client;
			this.TargetSpn = targetSpn;
			this._clientCred = clientCred;
			this.RequiredCapabilities = SecurityCapabilities.MutualAuthentication | SecurityCapabilities.Integrity;
			this._callback = callback;
		}

		private readonly KerberosClientCred _clientCred;

		/// <inheritdoc/>
		public override string UserName => this.Credential.UserName.UserName;

		/// <inheritdoc/>
		public sealed override int Legs => 2;

		/// <summary>
		/// Gets the Kerberos credential to authenticate with.
		/// </summary>
		public KerberosCredential Credential { get; }
		private readonly KerberosClient _client;

		/// <inheritdoc/>
		public sealed override SecurityCapabilities SupportedCapabilities => SecurityCapabilities.Delegation | SecurityCapabilities.MutualAuthentication | SecurityCapabilities.ReplayDetection | SecurityCapabilities.SequenceDetection | SecurityCapabilities.Confidentiality | SecurityCapabilities.Integrity;

		private readonly IKerberosCallback? _callback;
		/// <inheritdoc/>
		public sealed override SecurityCapabilities NegotiatedCapabilities => this.IsComplete ? this.RequiredCapabilities : SecurityCapabilities.None;
		/// <summary>
		/// Gets a value indicating whether confidentiality has been negotiated.
		/// </summary>
		public bool NegotiatedConfidentiality => 0 != (this.NegotiatedCapabilities & SecurityCapabilities.Confidentiality);
		/// <summary>
		/// Gets a value indicating whether integrity has been negotiated.
		/// </summary>
		public bool NegotiatedIntegrity => 0 != (this.NegotiatedCapabilities & SecurityCapabilities.Integrity);

		/// <inheritdoc/>
		public sealed override byte RpcAuthType => 0x10;

		/// <summary>
		/// Gets the OID for Kerberos.
		/// </summary>
		public static readonly Asn1Oid KerberosOid = new Asn1Oid("1.2.840.113554.1.2.2");
		/// <summary>
		/// Gets the OID for [MS-KILE]
		/// </summary>
		public static readonly Asn1Oid MskileOid = new("1.2.840.48018.1.2.2");

		private SessionKey VerifySessionKey()
		{
			var sessionKey = this._sessionKey;
			if (sessionKey == null)
				throw new InvalidOperationException(Messages.Krb5_ContextNotInitialized);
			return sessionKey;
		}

		private bool _isComplete;
		/// <inheritdoc/>
		public sealed override bool IsComplete => this._isComplete;

		/// <inheritdoc/>
		public sealed override SecurityPrincipalName? TargetSpn { get; set; }

		/// <inheritdoc/>
		private UserPrincipalName? U2UserName => this._clientCred.U2UserName;

		private byte[]? _token;
		/// <inheritdoc/>
		public sealed override ReadOnlySpan<byte> Token => this._token;

		/// <inheritdoc/>
		public sealed override bool HasSessionKey => true;
		/// <inheritdoc/>
		public sealed override int SessionKeySize => this.VerifySessionKey().key.keyvalue.Length;

		private TicketInfo? _ticket;
		public TicketInfo? Ticket => this._ticket ?? this._clientCred.Ticket;

		/// <summary>
		/// Session key generated by the client using the same EncProfile as the ticket
		/// </summary>
		public SessionKey? InitiatorSubkey { get; private set; }
		public SessionKey? AcceptorSubkey { get; private set; }
		private SessionKey? _sessionKey;
		private bool _useAcceptorSubkey = true;

		public int SendSeqNbr { get; private set; }
		public uint RecvSeqNbr { get; private set; }

		private uint GetSeqNbrForSend()
		{
			var seqNbr = (uint)(this.SendSeqNbr++);
#if DEBUG
			Debug.WriteLine($"[krb5]: Sending with seq # {seqNbr}");
#endif
			return seqNbr;
		}

		private KerberosTime _now;

		/// <inheritdoc/>
		/// <exception cref="InvalidOperationException"><see cref="TargetSpn"/> is null or empty.</exception>
		protected sealed override ReadOnlySpan<byte> InitializeImpl()
		{
			var ticket = this.Ticket;
			this._now = KerberosTime.Now();

			if (ticket is null)
			{
				var u2UserName = this._clientCred.U2UserName;
				Debug.Assert(u2UserName != null);

				return this._token = Asn1DerEncoder.EncodeTlv(new Asn1.Krb5Token
				{
					mechId = new Asn1Oid(TGT_REQ.U2uOid),
					tokenId = GssapiTokenId.TgtReq,
					tgtreq = new TGT_REQ(
						Structs.PrincipalName(PrincipalNameType.MsPrincipal, u2UserName.UserName),
						new GeneralString(this.U2UserName.Realm ?? this.Credential.Realm ?? string.Empty))
				}).ToArray();
			}
			else
			{
				var initiatorSubkey = this._sessionKey = this.InitiatorSubkey = ticket.GenerateSessionKey();
				int sendSeqNbr = KerberosClient.GenerateNonce();
				this.SendSeqNbr = sendSeqNbr;
				APOptions options = this.IsMutualAuthRequired
					? APOptions.MutualRequired
					: APOptions.None
					;
				if (this._clientCred.U2UserName != null)
					options |= APOptions.UseSessionKey;
				var gssFlags = this.RequiredCapabilities;

				DelegationToken? delgToken;
				if (this._clientCred.ForwardedTickets != null)
				{
					delgToken = new DelegationToken()
					{
						Bytes = KerberosClient.ExportKirbi(this._clientCred.ForwardedTickets)
					};
				}
				else
				{
					delgToken = null;
				}

				var apreq = KerberosClient.CreateAPReq(
					ticket,
					this.TargetSpn,
					initiatorSubkey.key,
					this._now,
					sendSeqNbr,
					options,
					gssFlags,
					this.ChannelBinding,
					delgToken
					);

				var encoder = Asn1DerEncoding.CreateDerEncoder();
				encoder.EncodeValueTlv(apreq);

				this._callback?.OnSendingApreq(this.CorrelationId, this, this.TargetSpn, ticket, this.Credential, gssFlags, initiatorSubkey, sendSeqNbr);

				if (!this.IsDceRpcStyle)
				{
					return this._token = Asn1DerEncoder.EncodeTlv(new Asn1.Krb5Token
					{
						mechId = KerberosOid,
						tokenId = GssapiTokenId.APReq,
						apreq = apreq
					}).ToArray();
				}
				else
				{
					return this._token = encoder.GetBytes().ToArray();
				}
			}
		}

		/// <inheritdoc/>
		protected sealed override ReadOnlySpan<byte> InitializeWithToken(ReadOnlySpan<byte> token)
		{
			if (this.Ticket is null)
			{
				// This is U2U
				Asn1.Krb5Token tokenStruc = Asn1DerDecoder.DecodeTlv<Asn1.Krb5Token>(token.ToArray());
				if (tokenStruc.tokenId == GssapiTokenId.TgtRep)
				{
					var tgtrep = tokenStruc.tgtrep;
					var serverTicket = tgtrep.ticket;

					var cancellationToken = CancellationToken.None;

					var krb = this._client;
					var ticket = Task.Factory.StartNew(() => krb.RequestTicket(this._clientCred.Tgt, this.U2UserName, serverTicket.realm, null, new TicketParameters { addlTicketStruc = serverTicket, Options = KerberosClient.DefaultU2uTicketOptions }, cancellationToken)).Unwrap().Result;
					this._ticket = ticket;

					return this.InitializeImpl();
				}
				else if (tokenStruc.tokenId == GssapiTokenId.Error)
				{
					throw tokenStruc.error.GetException();
				}
				else
				{
					throw new FormatException($"The server sent a token with an unrecognized or unsupported ID: {tokenStruc.tokenId} (0x{(uint)tokenStruc.tokenId:X4})");
				}
			}
			else
			{
				AP_REP_Tagged15 aprep;
				byte[]? tokenBytes;
				if (!this.IsDceRpcStyle)
				{
					Asn1.Krb5Token tokenStruc = Asn1DerDecoder.DecodeTlv<Asn1.Krb5Token>(token.ToArray());
					if (tokenStruc.tokenId == GssapiTokenId.APRep)
					{
						aprep = tokenStruc.aprep.Value;
					}
					else if (tokenStruc.tokenId == GssapiTokenId.Error)
					{
						throw tokenStruc.error.GetException();
					}
					else
					{
						throw new FormatException($"The server sent a token with an unrecognized or unsupported ID: {tokenStruc.tokenId} (0x{(uint)tokenStruc.tokenId:X4})");
					}
				}
				else
				{
					aprep = Asn1DerDecoder.DecodeTlv<AP_REP>(token.ToArray()).Value;
				}

				var aprep_encPart = this.Ticket.SessionKey.DecryptTlv<EncAPRepPart>(
					KeyUsage.APRep_EncPart,
					aprep.enc_part
					).Value;

				bool timestampMatches = (aprep_encPart.cusec == this._now.usec) && (aprep_encPart.ctime == this._now.dt);
				if (!timestampMatches)
					throw new SecurityException("The timestamp returned by the server does not match the timestamp sent by the client.");

				// In general, according to [RFC 4120] § 5.1.2, missing fields are replaced with the default value
				this.RecvSeqNbr = aprep_encPart.seq_number ?? 0;

				if (aprep_encPart.subkey != null)
				{
					this.AcceptorSubkey = this._client.CreateSessionKeyFor(aprep_encPart.subkey);
					this._sessionKey = this.AcceptorSubkey;
					this._useAcceptorSubkey = true;
				}

				this._callback?.OnReceivedAprep(this.CorrelationId, this, this.RecvSeqNbr, this.AcceptorSubkey);

				if (this.IsDceRpcStyle)
				{
					var now = KerberosTime.Now();
					aprep_encPart.subkey = null;
					aprep_encPart.ctime = now.dt;
					aprep_encPart.cusec = now.usec;
					AP_REP aprep2 = new AP_REP(
						new AP_REP_Tagged15(
							5,
							(byte)KrbMessageType.Aprep,
							this.Ticket.SessionKey.EncryptTlv(
								KeyUsage.APRep_EncPart,
								new EncAPRepPart(
									aprep_encPart
						))));
					var respToken = Asn1DerEncoder.EncodeTlv(aprep2);
					tokenBytes = respToken.ToArray();
				}
				else
				{
					tokenBytes = null;
				}

				this._isComplete = true;
				return this._token = tokenBytes;
			}
		}

		/// <inheritdoc/>
		protected sealed override ReadOnlySpan<byte> GetSessionKeyImpl()
		{
			return this.VerifySessionKey().key.keyvalue;
		}

		private static Exception MakeBadMacSizeException(string paramName)
		{
			return new ArgumentException("The buffer provided for the message authentication code does not match the size required by the security provider.", paramName);
		}


		/// <inheritdoc/>
		public sealed override int SignTokenSize => this.VerifySessionKey().EncryptionProfile.SignTokenSize;

		/// <inheritdoc/>
		/// <remarks>
		/// Kerberos supports header rotation to effectively combine the header and trailer into a single token buffer.
		/// </remarks>
		public sealed override int GetWrapTokenSize(WrapOptions options)
		{
			this.GetWrapBufferSizes(options, out var header, out var trailer);
			return header + trailer;
		}
		/// <inheritdoc/>
		public override void GetWrapBufferSizes(WrapOptions options, out int requiredHeaderSize, out int requiredTrailerSize)
		{
			var encProfile = this.VerifySessionKey().EncryptionProfile;
			encProfile.GetWrapBufferSizes(options, out requiredHeaderSize, out requiredTrailerSize);
		}

		/// <inheritdoc/>
		public sealed override void IncrementRecvSeqNbr()
		{
			var seqNbr = this.GetSeqNbrForReceive();
		}

		/// <inheritdoc/>
		public sealed override void SignMessage(
			in MessageSignParams signParams,
			MessageSignOptions options
			)
		{
			if (signParams.MacBuffer.Length != this.SignTokenSize)
				throw MakeBadMacSizeException(nameof(signParams));

			var sessionKey = this.VerifySessionKey();
			var flags = this._useAcceptorSubkey
				? (WrapFlags.AcceptorSubkey)
				: WrapFlags.None;

			var seqNbr = this.GetSeqNbrForSend();
			sessionKey.SignMessage(
				KeyUsage.InitiatorSign,
				seqNbr,
				flags,
				in signParams
				);
		}

		public sealed override void VerifyMessage(
			in MessageVerifyParams verifyParams,
			MessageSignOptions options)
		{
			if (verifyParams.MacBuffer.Length != this.SignTokenSize)
				throw MakeBadMacSizeException(nameof(verifyParams));

			var sessionKey = this.VerifySessionKey();
			var flags = WrapFlags.SentByAcceptor | (this._useAcceptorSubkey
				? (WrapFlags.AcceptorSubkey)
				: WrapFlags.None);

			uint seqNbr = GetSeqNbrForReceive();
			sessionKey.VerifySignature(
				KeyUsage.AcceptorSign,
				seqNbr,
				flags,
				verifyParams
				);
		}

		private uint GetSeqNbrForReceive()
		{
			return (uint)(this.RecvSeqNbr++);
		}

		/// <inheritdoc/>
		public sealed override void SealMessage(in MessageSealParams sealParams)
		{
			Debug.Assert(this.NegotiatedConfidentiality);
			var sessionKey = this.VerifySessionKey();

			uint seqNbr = this.GetSeqNbrForSend();
			var flags = this._useAcceptorSubkey
				? (WrapFlags.Sealed | WrapFlags.AcceptorSubkey)
				: WrapFlags.Sealed;
			sessionKey.SealMessage(
				KeyUsage.InitiatorSeal,
				seqNbr,
				flags,
				in sealParams
				);
		}

		/// <inheritdoc/>
		public sealed override void UnsealMessage(in MessageSealParams unsealParams)
		{
			Debug.Assert(this.NegotiatedConfidentiality);
			SessionKey sessionKey = this.VerifySessionKey();

			uint seqNbr = (uint)(this.RecvSeqNbr++);
			var flags = this._useAcceptorSubkey
				? (WrapFlags.Sealed | WrapFlags.AcceptorSubkey)
				: WrapFlags.Sealed;

			sessionKey.UnsealMessage(
				KeyUsage.AcceptorSeal,
				seqNbr,
				flags | WrapFlags.SentByAcceptor,
				in unsealParams);
		}

		public byte[] EncodeKrbPriv(byte[] bytes)
		{
			var now = KerberosTime.Now();
			EncKrbPrivPart encpriv = new EncKrbPrivPart(new EncKrbPrivPart_Tagged28(
				bytes,
				(this._client.Workstation ?? HostAddress.FromIPAddress(IPAddress.Any)).ToKrb5HostAddress(),
				now.AsDateTime(),
				now.usec,
				(uint)this.SendSeqNbr,
				null
				));
			var encprivBytes = this.InitiatorSubkey.EncryptTlv(KeyUsage.Priv, encpriv);
			var privBytes = Asn1DerEncoder.EncodeTlv(new KRB_PRIV(new KRB_PRIV_Tagged21(5, (byte)KrbMessageType.Priv, encprivBytes)));

			return privBytes.ToArray();
		}
	}
	/// <summary>
	/// Implements a Kerberos authentication client.
	/// </summary>
	/// <remarks>
	/// This class presents the RFC 4120 Kerberos mechanism OID.
	/// </remarks>
	public sealed class KerberosClientContext : KerberosClientContextBase
	{
		public KerberosClientContext(
			KerberosCredential credential,
			KerberosClient client,
			SecurityPrincipalName targetSpn,
			KerberosClientCred clientCred,
			IKerberosCallback? callback = null
			)
			: base(credential, client, targetSpn, clientCred, callback)
		{ }
		/// <inheritdoc/>
		public sealed override Asn1Oid MechOid => KerberosOid;
	}
	/// <summary>
	/// Implements a Kerberos authentication client.
	/// </summary>
	/// <remarks>
	/// This class presents the [MS-KILE] Kerberos mechanism OID.
	/// </remarks>
	public sealed class MskileClientContext : KerberosClientContextBase
	{
		public MskileClientContext(
			KerberosCredential credential,
			KerberosClient client,
			SecurityPrincipalName targetSpn,
			KerberosClientCred clientCred,
			IKerberosCallback? callback = null
			)
			: base(credential, client, targetSpn, clientCred, callback)
		{ }
		/// <inheritdoc/>
		public sealed override Asn1Oid MechOid => MskileOid;
	}
}
