//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Titanis.Security.Kerberos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Titanis.Security.Kerberos.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided checksum buffer is not large enough to hold a checksum..
        /// </summary>
        internal static string Krb5_ChecksumBufferTooSmall {
            get {
                return ResourceManager.GetString("Krb5_ChecksumBufferTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context is not initialized, and this functionality is not available..
        /// </summary>
        internal static string Krb5_ContextNotInitialized {
            get {
                return ResourceManager.GetString("Krb5_ContextNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This credential does not support the selected encryption profile..
        /// </summary>
        internal static string Krb5_CredETypeMismatch {
            get {
                return ResourceManager.GetString("Krb5_CredETypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an unknown token ID: &apos;{0:X2}&apos;..
        /// </summary>
        internal static string Krb5_GssapiTokenIdUnknown {
            get {
                return ResourceManager.GetString("Krb5_GssapiTokenIdUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The header and/or checksum buffers provided are not the correct size..
        /// </summary>
        internal static string Krb5_IncorrectCryptBuffers {
            get {
                return ResourceManager.GetString("Krb5_IncorrectCryptBuffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message checksum is invalid..
        /// </summary>
        internal static string Krb5_InvalidChecksum {
            get {
                return ResourceManager.GetString("Krb5_InvalidChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ciphertext is corrupt..
        /// </summary>
        internal static string Krb5_InvalidCiphertext {
            get {
                return ResourceManager.GetString("Krb5_InvalidCiphertext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sealed message appears to be corrupt..
        /// </summary>
        internal static string Krb5_InvalidSealedMessage {
            get {
                return ResourceManager.GetString("Krb5_InvalidSealedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Kerberos server did not return an AS-REP..
        /// </summary>
        internal static string Krb5_NoASRep {
            get {
                return ResourceManager.GetString("Krb5_NoASRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The KDC for realm &apos;{0}&apos; could not be located..
        /// </summary>
        internal static string Krb5_NoKdc {
            get {
                return ResourceManager.GetString("Krb5_NoKdc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server does not accept any preauthentication methods that the client supports..
        /// </summary>
        internal static string Krb5_NoSupportedPreauths {
            get {
                return ResourceManager.GetString("Krb5_NoSupportedPreauths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication context does not have a target host set..
        /// </summary>
        internal static string Krb5_NoTargetHost {
            get {
                return ResourceManager.GetString("Krb5_NoTargetHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication context does not have a target realm set..
        /// </summary>
        internal static string Krb5_NoTargetRealm {
            get {
                return ResourceManager.GetString("Krb5_NoTargetRealm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication context does not have a target SPN set..
        /// </summary>
        internal static string Krb5_NoTargetSpn {
            get {
                return ResourceManager.GetString("Krb5_NoTargetSpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Kerberos server did not return a TGS-REP..
        /// </summary>
        internal static string Krb5_NoTGSRep {
            get {
                return ResourceManager.GetString("Krb5_NoTGSRep", resourceCulture);
            }
        }
    }
}
