//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Titanis.DceRpc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Titanis.DceRpc.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RPC client is already connected to a channel..
        /// </summary>
        internal static string RpcClient_AlreadyConnected {
            get {
                return ResourceManager.GetString("RpcClient_AlreadyConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client channel has already been started..
        /// </summary>
        internal static string RpcClient_ChannelAlreadyStarted {
            get {
                return ResourceManager.GetString("RpcClient_ChannelAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interface is not supported..
        /// </summary>
        internal static string RpcClient_InterfaceNotSupported {
            get {
                return ResourceManager.GetString("RpcClient_InterfaceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This proxy object is not bound to a channel.  Use BindTo to bind to a channel.
        /// </summary>
        internal static string RpcClient_ProxyNotBound {
            get {
                return ResourceManager.GetString("RpcClient_ProxyNotBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RPC server has already been started..
        /// </summary>
        internal static string RpcServer_AlreadyRunning {
            get {
                return ResourceManager.GetString("RpcServer_AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PDU is not marked as the first fragment, but the call ID doesn&apos;t exist..
        /// </summary>
        internal static string RpcServer_BadFragCallId {
            get {
                return ResourceManager.GetString("RpcServer_BadFragCallId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fragment received was shorter than the header reported..
        /// </summary>
        internal static string RpcServer_IncompleteFragment {
            get {
                return ResourceManager.GetString("RpcServer_IncompleteFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fragment length does not match the size of the message..
        /// </summary>
        internal static string RpcServer_InvalidFragSize {
            get {
                return ResourceManager.GetString("RpcServer_InvalidFragSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version on the PDU header is incorrect..
        /// </summary>
        internal static string RpcServer_InvalidVersion {
            get {
                return ResourceManager.GetString("RpcServer_InvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The received fragment is too short..
        /// </summary>
        internal static string RpcServer_ReceivedFragTooShort {
            get {
                return ResourceManager.GetString("RpcServer_ReceivedFragTooShort", resourceCulture);
            }
        }
    }
}
