<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Titanis.Winterop.ErrorCodes\Titanis.Winterop.ErrorCodes.csproj" />
    <ProjectReference Include="..\Titanis.Winterop.Security\Titanis.Winterop.Security.csproj" />
  </ItemGroup>

</Project>
