<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\base\Titanis.Core\Titanis.Core.csproj" />
    <ProjectReference Include="..\..\..\base\Titanis.IO\Titanis.IO.csproj" />
    <ProjectReference Include="..\..\..\base\Titanis.Winterop.ErrorCodes\Titanis.Winterop.ErrorCodes.csproj" />
    <ProjectReference Include="..\..\..\base\Titanis.Winterop.Sam\Titanis.Winterop.Sam.csproj" />
    <ProjectReference Include="..\..\..\base\Titanis.Winterop.Security\Titanis.Winterop.Security.csproj" />
    <ProjectReference Include="..\..\..\build\Titanis.SourceGeneration.DceRpc\Titanis.SourceGeneration.DceRpc.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    <ProjectReference Include="..\..\..\build\Titanis.SourceGeneration.PduStruct\Titanis.SourceGeneration.PduStruct.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    <ProjectReference Include="..\..\..\crypto\Titanis.Crypto.Md5\Titanis.Crypto.Md5.csproj" />
    <ProjectReference Include="..\..\..\crypto\Titanis.Crypto.Rc4\Titanis.Crypto.Rc4.csproj" />
    <ProjectReference Include="..\..\..\formats\Titanis.Compression\Titanis.Compression.csproj" />
    <ProjectReference Include="..\..\Titanis.DceRpc.Core\Titanis.DceRpc.Core.csproj" />
    <ProjectReference Include="..\..\Titanis.Ldap.Core\Titanis.Ldap.Core.csproj" />
    <ProjectReference Include="..\..\Titanis.Msrpc.Core\Titanis.Msrpc.Core.csproj" />
    <ProjectReference Include="..\..\Titanis.Net\Titanis.Net.csproj" />
  </ItemGroup>

</Project>
