<Project Sdk="MSTest.Sdk/4.0.1">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TestingExtensionsProfile>None</TestingExtensionsProfile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="TestFileAccess.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="TestData\milchick-pkinit.ccache" />
    <None Remove="TestData\milchick.ccache" />
    <None Remove="TestData\milchick.pfx" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="TestData\milchick-pkinit.ccache" />
    <EmbeddedResource Include="TestData\milchick.ccache" />
    <EmbeddedResource Include="TestData\milchick.pfx" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\base\Titanis.Mocks\Titanis.Mocks.csproj" />
    <ProjectReference Include="..\..\Titanis.TestUtilities\Titanis.TestUtilities.csproj" />
    <ProjectReference Include="..\..\..\tools\security\Kerb\Kerb.csproj" />
  </ItemGroup>

</Project>
