<Project Sdk="MSTest.Sdk/4.0.1">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TestingExtensionsProfile>None</TestingExtensionsProfile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\tools\net\smb2\Smb2Client\Smb2Client.csproj" />
    <ProjectReference Include="..\..\Titanis.TestUtilities\Titanis.TestUtilities.csproj" />
  </ItemGroup>

</Project>
