//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Titanis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Titanis.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum value must be greater than or equal to the minimum value..
        /// </summary>
        internal static string ArgMinExceedsMaxErrorMessage {
            get {
                return ResourceManager.GetString("ArgMinExceedsMaxErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum value cannot exceed the maximum value..
        /// </summary>
        internal static string ArgMinMaxInvalidMessage {
            get {
                return ResourceManager.GetString("ArgMinMaxInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument requires a non-negative value..
        /// </summary>
        internal static string ArgNonnegRequiredMessage {
            get {
                return ResourceManager.GetString("ArgNonnegRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must be a positive integer greater than zero..
        /// </summary>
        internal static string ArgPositiveNonzeroRequiredMessage {
            get {
                return ResourceManager.GetString("ArgPositiveNonzeroRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length falls outside the range of the array..
        /// </summary>
        internal static string ArrayLengthOutOfRangeMessage {
            get {
                return ResourceManager.GetString("ArrayLengthOutOfRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start index is out of range..
        /// </summary>
        internal static string ArrayStartIndexOutOfRangeMessage {
            get {
                return ResourceManager.GetString("ArrayStartIndexOutOfRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start index and count falls outside the range of the buffer..
        /// </summary>
        internal static string BufferSpanOutOfRangeMessage {
            get {
                return ResourceManager.GetString("BufferSpanOutOfRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character is not a valid hexadecimal digit..
        /// </summary>
        internal static string HexParse_InvalidHexDigit {
            get {
                return ResourceManager.GetString("HexParse_InvalidHexDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character string must have an even number of characters..
        /// </summary>
        internal static string HexParse_InvalidSize {
            get {
                return ResourceManager.GetString("HexParse_InvalidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lambda expression must be a property access..
        /// </summary>
        internal static string PropertyAccessExpressionRequiredMessage1 {
            get {
                return ResourceManager.GetString("PropertyAccessExpressionRequiredMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The runnable object cannot be started because it is not in the Stopped state..
        /// </summary>
        internal static string ProtocolBase_NotStopped {
            get {
                return ResourceManager.GetString("ProtocolBase_NotStopped", resourceCulture);
            }
        }
    }
}
