<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\base\Titanis.Linterop.Fuse\Titanis.Linterop.Fuse.csproj" />
    <ProjectReference Include="..\Titanis.Ldap.Core\Titanis.Ldap.Core.csproj" />
    <ProjectReference Include="..\Titanis.Ldap\Titanis.Ldap.csproj" />
  </ItemGroup>

</Project>
