//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Titanis.Msrpc.Mstsch.Xml
{

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    [System.Xml.Serialization.XmlRootAttribute("Task", Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task", IsNullable = false)]
    public partial class taskType
    {

        private registrationInfoType registrationInfoField;

        private triggersType triggersField;

        private settingsType settingsField;

        private System.Xml.XmlElement dataField;

        private principalsType principalsField;

        private actionsType actionsField;

        private string versionField;

        public taskType()
        {
            this.versionField = "1.3";
        }

        /// <remarks/>
        public registrationInfoType RegistrationInfo
        {
            get
            {
                return this.registrationInfoField;
            }
            set
            {
                this.registrationInfoField = value;
            }
        }

        /// <remarks/>
        public triggersType Triggers
        {
            get
            {
                return this.triggersField;
            }
            set
            {
                this.triggersField = value;
            }
        }

        /// <remarks/>
        public settingsType Settings
        {
            get
            {
                return this.settingsField;
            }
            set
            {
                this.settingsField = value;
            }
        }

        /// <remarks/>
        public System.Xml.XmlElement Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        /// <remarks/>
        public principalsType Principals
        {
            get
            {
                return this.principalsField;
            }
            set
            {
                this.principalsField = value;
            }
        }

        /// <remarks/>
        public actionsType Actions
        {
            get
            {
                return this.actionsField;
            }
            set
            {
                this.actionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class registrationInfoType
    {

        private string uRIField;

        private string securityDescriptorField;

        private string sourceField;

        private System.DateTime dateField;

        private bool dateFieldSpecified;

        private string authorField;

        private string versionField;

        private string descriptionField;

        private string documentationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string URI
        {
            get
            {
                return this.uRIField;
            }
            set
            {
                this.uRIField = value;
            }
        }

        /// <remarks/>
        public string SecurityDescriptor
        {
            get
            {
                return this.securityDescriptorField;
            }
            set
            {
                this.securityDescriptorField = value;
            }
        }

        /// <remarks/>
        public string Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified
        {
            get
            {
                return this.dateFieldSpecified;
            }
            set
            {
                this.dateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Author
        {
            get
            {
                return this.authorField;
            }
            set
            {
                this.authorField = value;
            }
        }

        /// <remarks/>
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string Documentation
        {
            get
            {
                return this.documentationField;
            }
            set
            {
                this.documentationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class headerFieldType
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(showMessageType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sendEmailType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(comHandlerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(execType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public abstract partial class actionBaseType
    {

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class showMessageType : actionBaseType
    {

        private string titleField;

        private string bodyField;

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class sendEmailType : actionBaseType
    {

        private string serverField;

        private string subjectField;

        private string toField;

        private string ccField;

        private string bccField;

        private string replyToField;

        private string fromField;

        private headerFieldType[] headerFieldsField;

        private string bodyField;

        private string[] attachmentsField;

        /// <remarks/>
        public string Server
        {
            get
            {
                return this.serverField;
            }
            set
            {
                this.serverField = value;
            }
        }

        /// <remarks/>
        public string Subject
        {
            get
            {
                return this.subjectField;
            }
            set
            {
                this.subjectField = value;
            }
        }

        /// <remarks/>
        public string To
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }

        /// <remarks/>
        public string Cc
        {
            get
            {
                return this.ccField;
            }
            set
            {
                this.ccField = value;
            }
        }

        /// <remarks/>
        public string Bcc
        {
            get
            {
                return this.bccField;
            }
            set
            {
                this.bccField = value;
            }
        }

        /// <remarks/>
        public string ReplyTo
        {
            get
            {
                return this.replyToField;
            }
            set
            {
                this.replyToField = value;
            }
        }

        /// <remarks/>
        public string From
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("HeaderField", IsNullable = false)]
        public headerFieldType[] HeaderFields
        {
            get
            {
                return this.headerFieldsField;
            }
            set
            {
                this.headerFieldsField = value;
            }
        }

        /// <remarks/>
        public string Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("File", IsNullable = false)]
        public string[] Attachments
        {
            get
            {
                return this.attachmentsField;
            }
            set
            {
                this.attachmentsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class comHandlerType : actionBaseType
    {

        private string classIdField;

        private System.Xml.XmlElement dataField;

        /// <remarks/>
        public string ClassId
        {
            get
            {
                return this.classIdField;
            }
            set
            {
                this.classIdField = value;
            }
        }

        /// <remarks/>
        public System.Xml.XmlElement Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class execType : actionBaseType
    {

        private string commandField;

        private string argumentsField;

        private string workingDirectoryField;

        /// <remarks/>
        public string Command
        {
            get
            {
                return this.commandField;
            }
            set
            {
                this.commandField = value;
            }
        }

        /// <remarks/>
        public string Arguments
        {
            get
            {
                return this.argumentsField;
            }
            set
            {
                this.argumentsField = value;
            }
        }

        /// <remarks/>
        public string WorkingDirectory
        {
            get
            {
                return this.workingDirectoryField;
            }
            set
            {
                this.workingDirectoryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class actionsType
    {

        private actionBaseType[] itemsField;

        private string contextField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ComHandler", typeof(comHandlerType))]
        [System.Xml.Serialization.XmlElementAttribute("Exec", typeof(execType))]
        [System.Xml.Serialization.XmlElementAttribute("SendEmail", typeof(sendEmailType))]
        [System.Xml.Serialization.XmlElementAttribute("ShowMessage", typeof(showMessageType))]
        public actionBaseType[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "IDREF")]
        public string Context
        {
            get
            {
                return this.contextField;
            }
            set
            {
                this.contextField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class principalType
    {

        private string userIdField;

        private logonType logonTypeField;

        private bool logonTypeFieldSpecified;

        private string groupIdField;

        private string displayNameField;

        private runLevelType runLevelField;

        private bool runLevelFieldSpecified;

        private processTokenSidType processTokenSidTypeField;

        private bool processTokenSidTypeFieldSpecified;

        private privilegeType[] requiredPrivilegesField;

        private string idField;

        /// <remarks/>
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        public logonType LogonType
        {
            get
            {
                return this.logonTypeField;
            }
            set
            {
                this.logonTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LogonTypeSpecified
        {
            get
            {
                return this.logonTypeFieldSpecified;
            }
            set
            {
                this.logonTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string GroupId
        {
            get
            {
                return this.groupIdField;
            }
            set
            {
                this.groupIdField = value;
            }
        }

        /// <remarks/>
        public string DisplayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }

        /// <remarks/>
        public runLevelType RunLevel
        {
            get
            {
                return this.runLevelField;
            }
            set
            {
                this.runLevelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RunLevelSpecified
        {
            get
            {
                return this.runLevelFieldSpecified;
            }
            set
            {
                this.runLevelFieldSpecified = value;
            }
        }

        /// <remarks/>
        public processTokenSidType ProcessTokenSidType
        {
            get
            {
                return this.processTokenSidTypeField;
            }
            set
            {
                this.processTokenSidTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProcessTokenSidTypeSpecified
        {
            get
            {
                return this.processTokenSidTypeFieldSpecified;
            }
            set
            {
                this.processTokenSidTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Privilege", IsNullable = false)]
        public privilegeType[] RequiredPrivileges
        {
            get
            {
                return this.requiredPrivilegesField;
            }
            set
            {
                this.requiredPrivilegesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public enum runLevelType
    {

        /// <remarks/>
        LeastPrivilege,

        /// <remarks/>
        HighestAvailable,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public enum processTokenSidType
    {

        /// <remarks/>
        None,

        /// <remarks/>
        Unrestricted,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public enum privilegeType
    {

        /// <remarks/>
        SeCreateTokenPrivilege,

        /// <remarks/>
        SeAssignPrimaryTokenPrivilege,

        /// <remarks/>
        SeLockMemoryPrivilege,

        /// <remarks/>
        SeIncreaseQuotaPrivilege,

        /// <remarks/>
        SeUnsolicitedInputPrivilege,

        /// <remarks/>
        SeMachineAccountPrivilege,

        /// <remarks/>
        SeTcbPrivilege,

        /// <remarks/>
        SeSecurityPrivilege,

        /// <remarks/>
        SeTakeOwnershipPrivilege,

        /// <remarks/>
        SeLoadDriverPrivilege,

        /// <remarks/>
        SeSystemProfilePrivilege,

        /// <remarks/>
        SeSystemtimePrivilege,

        /// <remarks/>
        SeProfileSingleProcessPrivilege,

        /// <remarks/>
        SeIncreaseBasePriorityPrivilege,

        /// <remarks/>
        SeCreatePagefilePrivilege,

        /// <remarks/>
        SeCreatePermanentPrivilege,

        /// <remarks/>
        SeBackupPrivilege,

        /// <remarks/>
        SeRestorePrivilege,

        /// <remarks/>
        SeShutdownPrivilege,

        /// <remarks/>
        SeDebugPrivilege,

        /// <remarks/>
        SeAuditPrivilege,

        /// <remarks/>
        SeSystemEnvironmentPrivilege,

        /// <remarks/>
        SeChangeNotifyPrivilege,

        /// <remarks/>
        SeRemoteShutdownPrivilege,

        /// <remarks/>
        SeUndockPrivilege,

        /// <remarks/>
        SeSyncAgentPrivilege,

        /// <remarks/>
        SeEnableDelegationPrivilege,

        /// <remarks/>
        SeManageVolumePrivilege,

        /// <remarks/>
        SeImpersonatePrivilege,

        /// <remarks/>
        SeCreateGlobalPrivilege,

        /// <remarks/>
        SeTrustedCredManAccessPrivilege,

        /// <remarks/>
        SeRelabelPrivilege,

        /// <remarks/>
        SeIncreaseWorkingSetPrivilege,

        /// <remarks/>
        SeTimeZonePrivilege,

        /// <remarks/>
        SeCreateSymbolicLinkPrivilege,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class principalsType
    {

        private principalType principalField;

        /// <remarks/>
        public principalType Principal
        {
            get
            {
                return this.principalField;
            }
            set
            {
                this.principalField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class networkSettingsType
    {

        private string nameField;

        private string idField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class idleSettingsType
    {

        private string durationField;

        private string waitTimeoutField;

        private bool stopOnIdleEndField;

        private bool restartOnIdleField;

        public idleSettingsType()
        {
            this.durationField = "PT10M";
            this.waitTimeoutField = "PT1H";
            this.stopOnIdleEndField = true;
            this.restartOnIdleField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT10M")]
        public string Duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT1H")]
        public string WaitTimeout
        {
            get
            {
                return this.waitTimeoutField;
            }
            set
            {
                this.waitTimeoutField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool StopOnIdleEnd
        {
            get
            {
                return this.stopOnIdleEndField;
            }
            set
            {
                this.stopOnIdleEndField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool RestartOnIdle
        {
            get
            {
                return this.restartOnIdleField;
            }
            set
            {
                this.restartOnIdleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class restartType
    {

        private string intervalField;

        private byte countField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string Interval
        {
            get
            {
                return this.intervalField;
            }
            set
            {
                this.intervalField = value;
            }
        }

        /// <remarks/>
        public byte Count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class settingsType
    {

        private bool allowStartOnDemandField;

        private restartType restartOnFailureField;

        private multipleInstancesPolicyType multipleInstancesPolicyField;

        private bool disallowStartIfOnBatteriesField;

        private bool stopIfGoingOnBatteriesField;

        private bool allowHardTerminateField;

        private bool startWhenAvailableField;

        private string networkProfileNameField;

        private bool runOnlyIfNetworkAvailableField;

        private bool wakeToRunField;

        private bool enabledField;

        private bool hiddenField;

        private string deleteExpiredTaskAfterField;

        private idleSettingsType idleSettingsField;

        private networkSettingsType networkSettingsField;

        private string executionTimeLimitField;

        private sbyte priorityField;

        private bool runOnlyIfIdleField;

        private bool useUnifiedSchedulingEngineField;

        private bool disallowStartOnRemoteAppSessionField;

        public settingsType()
        {
            this.allowStartOnDemandField = true;
            this.multipleInstancesPolicyField = multipleInstancesPolicyType.IgnoreNew;
            this.disallowStartIfOnBatteriesField = true;
            this.stopIfGoingOnBatteriesField = true;
            this.allowHardTerminateField = true;
            this.startWhenAvailableField = false;
            this.runOnlyIfNetworkAvailableField = false;
            this.wakeToRunField = false;
            this.enabledField = true;
            this.hiddenField = false;
            this.deleteExpiredTaskAfterField = "PT0S";
            this.executionTimeLimitField = "PT72H";
            this.priorityField = ((sbyte)(7));
            this.runOnlyIfIdleField = false;
            this.useUnifiedSchedulingEngineField = false;
            this.disallowStartOnRemoteAppSessionField = false;
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool AllowStartOnDemand
        {
            get
            {
                return this.allowStartOnDemandField;
            }
            set
            {
                this.allowStartOnDemandField = value;
            }
        }

        /// <remarks/>
        public restartType RestartOnFailure
        {
            get
            {
                return this.restartOnFailureField;
            }
            set
            {
                this.restartOnFailureField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(multipleInstancesPolicyType.IgnoreNew)]
        public multipleInstancesPolicyType MultipleInstancesPolicy
        {
            get
            {
                return this.multipleInstancesPolicyField;
            }
            set
            {
                this.multipleInstancesPolicyField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool DisallowStartIfOnBatteries
        {
            get
            {
                return this.disallowStartIfOnBatteriesField;
            }
            set
            {
                this.disallowStartIfOnBatteriesField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool StopIfGoingOnBatteries
        {
            get
            {
                return this.stopIfGoingOnBatteriesField;
            }
            set
            {
                this.stopIfGoingOnBatteriesField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool AllowHardTerminate
        {
            get
            {
                return this.allowHardTerminateField;
            }
            set
            {
                this.allowHardTerminateField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool StartWhenAvailable
        {
            get
            {
                return this.startWhenAvailableField;
            }
            set
            {
                this.startWhenAvailableField = value;
            }
        }

        /// <remarks/>
        public string NetworkProfileName
        {
            get
            {
                return this.networkProfileNameField;
            }
            set
            {
                this.networkProfileNameField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool RunOnlyIfNetworkAvailable
        {
            get
            {
                return this.runOnlyIfNetworkAvailableField;
            }
            set
            {
                this.runOnlyIfNetworkAvailableField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool WakeToRun
        {
            get
            {
                return this.wakeToRunField;
            }
            set
            {
                this.wakeToRunField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Hidden
        {
            get
            {
                return this.hiddenField;
            }
            set
            {
                this.hiddenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT0S")]
        public string DeleteExpiredTaskAfter
        {
            get
            {
                return this.deleteExpiredTaskAfterField;
            }
            set
            {
                this.deleteExpiredTaskAfterField = value;
            }
        }

        /// <remarks/>
        public idleSettingsType IdleSettings
        {
            get
            {
                return this.idleSettingsField;
            }
            set
            {
                this.idleSettingsField = value;
            }
        }

        /// <remarks/>
        public networkSettingsType NetworkSettings
        {
            get
            {
                return this.networkSettingsField;
            }
            set
            {
                this.networkSettingsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT72H")]
        public string ExecutionTimeLimit
        {
            get
            {
                return this.executionTimeLimitField;
            }
            set
            {
                this.executionTimeLimitField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(sbyte), "7")]
        public sbyte Priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool RunOnlyIfIdle
        {
            get
            {
                return this.runOnlyIfIdleField;
            }
            set
            {
                this.runOnlyIfIdleField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool UseUnifiedSchedulingEngine
        {
            get
            {
                return this.useUnifiedSchedulingEngineField;
            }
            set
            {
                this.useUnifiedSchedulingEngineField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool DisallowStartOnRemoteAppSession
        {
            get
            {
                return this.disallowStartOnRemoteAppSessionField;
            }
            set
            {
                this.disallowStartOnRemoteAppSessionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public enum multipleInstancesPolicyType
    {

        /// <remarks/>
        Parallel,

        /// <remarks/>
        Queue,

        /// <remarks/>
        IgnoreNew,

        /// <remarks/>
        StopExisting,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class monthlyDayOfWeekScheduleType
    {

        private string[] weeksField;

        private daysOfWeekType daysOfWeekField;

        private monthsType monthsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Week", IsNullable = false)]
        public string[] Weeks
        {
            get
            {
                return this.weeksField;
            }
            set
            {
                this.weeksField = value;
            }
        }

        /// <remarks/>
        public daysOfWeekType DaysOfWeek
        {
            get
            {
                return this.daysOfWeekField;
            }
            set
            {
                this.daysOfWeekField = value;
            }
        }

        /// <remarks/>
        public monthsType Months
        {
            get
            {
                return this.monthsField;
            }
            set
            {
                this.monthsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class daysOfWeekType
    {

        private object mondayField;

        private object tuesdayField;

        private object wednesdayField;

        private object thursdayField;

        private object fridayField;

        private object saturdayField;

        private object sundayField;

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object Monday
        {
            get
            {
                return this.mondayField;
            }
            set
            {
                this.mondayField = value;
            }
        }

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object Tuesday
        {
            get
            {
                return this.tuesdayField;
            }
            set
            {
                this.tuesdayField = value;
            }
        }

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object Wednesday
        {
            get
            {
                return this.wednesdayField;
            }
            set
            {
                this.wednesdayField = value;
            }
        }

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object Thursday
        {
            get
            {
                return this.thursdayField;
            }
            set
            {
                this.thursdayField = value;
            }
        }

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object Friday
        {
            get
            {
                return this.fridayField;
            }
            set
            {
                this.fridayField = value;
            }
        }

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object Saturday
        {
            get
            {
                return this.saturdayField;
            }
            set
            {
                this.saturdayField = value;
            }
        }

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object Sunday
        {
            get
            {
                return this.sundayField;
            }
            set
            {
                this.sundayField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class monthsType
    {

        private object januaryField;

        private object februaryField;

        private object marchField;

        private object aprilField;

        private object mayField;

        private object juneField;

        private object julyField;

        private object augustField;

        private object septemberField;

        private object octoberField;

        private object novemberField;

        private object decemberField;

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object January
        {
            get
            {
                return this.januaryField;
            }
            set
            {
                this.januaryField = value;
            }
        }

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object February
        {
            get
            {
                return this.februaryField;
            }
            set
            {
                this.februaryField = value;
            }
        }

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object March
        {
            get
            {
                return this.marchField;
            }
            set
            {
                this.marchField = value;
            }
        }

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object April
        {
            get
            {
                return this.aprilField;
            }
            set
            {
                this.aprilField = value;
            }
        }

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object May
        {
            get
            {
                return this.mayField;
            }
            set
            {
                this.mayField = value;
            }
        }

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object June
        {
            get
            {
                return this.juneField;
            }
            set
            {
                this.juneField = value;
            }
        }

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object July
        {
            get
            {
                return this.julyField;
            }
            set
            {
                this.julyField = value;
            }
        }

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object August
        {
            get
            {
                return this.augustField;
            }
            set
            {
                this.augustField = value;
            }
        }

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object September
        {
            get
            {
                return this.septemberField;
            }
            set
            {
                this.septemberField = value;
            }
        }

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object October
        {
            get
            {
                return this.octoberField;
            }
            set
            {
                this.octoberField = value;
            }
        }

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object November
        {
            get
            {
                return this.novemberField;
            }
            set
            {
                this.novemberField = value;
            }
        }

        /// <remarks/>
        // CODEGEN Warning: 'fixed' attribute supported only for primitive types.  Ignoring fixed='' attribute.
        public object December
        {
            get
            {
                return this.decemberField;
            }
            set
            {
                this.decemberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class monthlyScheduleType
    {

        private string[] daysOfMonthField;

        private monthsType monthsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Day", IsNullable = false)]
        public string[] DaysOfMonth
        {
            get
            {
                return this.daysOfMonthField;
            }
            set
            {
                this.daysOfMonthField = value;
            }
        }

        /// <remarks/>
        public monthsType Months
        {
            get
            {
                return this.monthsField;
            }
            set
            {
                this.monthsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class weeklyScheduleType
    {

        private byte weeksIntervalField;

        private bool weeksIntervalFieldSpecified;

        private daysOfWeekType daysOfWeekField;

        /// <remarks/>
        public byte WeeksInterval
        {
            get
            {
                return this.weeksIntervalField;
            }
            set
            {
                this.weeksIntervalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeeksIntervalSpecified
        {
            get
            {
                return this.weeksIntervalFieldSpecified;
            }
            set
            {
                this.weeksIntervalFieldSpecified = value;
            }
        }

        /// <remarks/>
        public daysOfWeekType DaysOfWeek
        {
            get
            {
                return this.daysOfWeekField;
            }
            set
            {
                this.daysOfWeekField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class dailyScheduleType
    {

        private uint daysIntervalField;

        private bool daysIntervalFieldSpecified;

        /// <remarks/>
        public uint DaysInterval
        {
            get
            {
                return this.daysIntervalField;
            }
            set
            {
                this.daysIntervalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DaysIntervalSpecified
        {
            get
            {
                return this.daysIntervalFieldSpecified;
            }
            set
            {
                this.daysIntervalFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class namedValue
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class repetitionType
    {

        private string intervalField;

        private string durationField;

        private bool stopAtDurationEndField;

        public repetitionType()
        {
            this.stopAtDurationEndField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string Interval
        {
            get
            {
                return this.intervalField;
            }
            set
            {
                this.intervalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string Duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool StopAtDurationEnd
        {
            get
            {
                return this.stopAtDurationEndField;
            }
            set
            {
                this.stopAtDurationEndField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(calendarTriggerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sessionStateChangeTriggerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(logonTriggerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(eventTriggerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(timeTriggerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(idleTriggerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(registrationTriggerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(bootTriggerType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public abstract partial class triggerBaseType
    {

        private bool enabledField;

		internal System.DateTime startBoundaryField;

		internal bool startBoundaryFieldSpecified;

		internal System.DateTime endBoundaryField;

		internal bool endBoundaryFieldSpecified;

        private repetitionType repetitionField;

        private string executionTimeLimitField;

        private string idField;

        public triggerBaseType()
        {
            this.enabledField = true;
            this.executionTimeLimitField = "PT72H";
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }

        /// <remarks/>
        public System.DateTime StartBoundary
        {
            get
            {
                return this.startBoundaryField;
            }
            set
            {
                this.startBoundaryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartBoundarySpecified
        {
            get
            {
                return this.startBoundaryFieldSpecified;
            }
            set
            {
                this.startBoundaryFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime EndBoundary
        {
            get
            {
                return this.endBoundaryField;
            }
            set
            {
                this.endBoundaryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndBoundarySpecified
        {
            get
            {
                return this.endBoundaryFieldSpecified;
            }
            set
            {
                this.endBoundaryFieldSpecified = value;
            }
        }

        /// <remarks/>
        public repetitionType Repetition
        {
            get
            {
                return this.repetitionField;
            }
            set
            {
                this.repetitionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT72H")]
        public string ExecutionTimeLimit
        {
            get
            {
                return this.executionTimeLimitField;
            }
            set
            {
                this.executionTimeLimitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class calendarTriggerType : triggerBaseType
    {

        private string randomDelayField;

        private object itemField;

        public calendarTriggerType()
        {
            this.randomDelayField = "PT0M";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT0M")]
        public string RandomDelay
        {
            get
            {
                return this.randomDelayField;
            }
            set
            {
                this.randomDelayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScheduleByDay", typeof(dailyScheduleType))]
        [System.Xml.Serialization.XmlElementAttribute("ScheduleByMonth", typeof(monthlyScheduleType))]
        [System.Xml.Serialization.XmlElementAttribute("ScheduleByMonthDayOfWeek", typeof(monthlyDayOfWeekScheduleType))]
        [System.Xml.Serialization.XmlElementAttribute("ScheduleByWeek", typeof(weeklyScheduleType))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class sessionStateChangeTriggerType : triggerBaseType
    {

        private string userIdField;

        private string delayField;

        private sessionStateChangeType stateChangeField;

        public sessionStateChangeTriggerType()
        {
            this.delayField = "PT0M";
        }

        /// <remarks/>
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT0M")]
        public string Delay
        {
            get
            {
                return this.delayField;
            }
            set
            {
                this.delayField = value;
            }
        }

        /// <remarks/>
        public sessionStateChangeType StateChange
        {
            get
            {
                return this.stateChangeField;
            }
            set
            {
                this.stateChangeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public enum sessionStateChangeType
    {

        /// <remarks/>
        ConsoleConnect,

        /// <remarks/>
        ConsoleDisconnect,

        /// <remarks/>
        RemoteConnect,

        /// <remarks/>
        RemoteDisconnect,

        /// <remarks/>
        SessionLock,

        /// <remarks/>
        SessionUnlock,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class logonTriggerType : triggerBaseType
    {

        private string userIdField;

        private string delayField;

        public logonTriggerType()
        {
            this.delayField = "PT0M";
        }

        /// <remarks/>
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT0M")]
        public string Delay
        {
            get
            {
                return this.delayField;
            }
            set
            {
                this.delayField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class eventTriggerType : triggerBaseType
    {

        private string subscriptionField;

        private string delayField;

        private string periodOfOccurrenceField;

        private byte numberOfOccurrencesField;

        private string matchingElementField;

        private namedValue[] valueQueriesField;

        public eventTriggerType()
        {
            this.delayField = "PT0M";
            this.periodOfOccurrenceField = "PT0M";
            this.numberOfOccurrencesField = ((byte)(1));
        }

        /// <remarks/>
        public string Subscription
        {
            get
            {
                return this.subscriptionField;
            }
            set
            {
                this.subscriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT0M")]
        public string Delay
        {
            get
            {
                return this.delayField;
            }
            set
            {
                this.delayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT0M")]
        public string PeriodOfOccurrence
        {
            get
            {
                return this.periodOfOccurrenceField;
            }
            set
            {
                this.periodOfOccurrenceField = value;
            }
        }

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(typeof(byte), "1")]
        public byte NumberOfOccurrences
        {
            get
            {
                return this.numberOfOccurrencesField;
            }
            set
            {
                this.numberOfOccurrencesField = value;
            }
        }

        /// <remarks/>
        public string MatchingElement
        {
            get
            {
                return this.matchingElementField;
            }
            set
            {
                this.matchingElementField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Value", IsNullable = false)]
        public namedValue[] ValueQueries
        {
            get
            {
                return this.valueQueriesField;
            }
            set
            {
                this.valueQueriesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class timeTriggerType : triggerBaseType
    {

        private string randomDelayField;

        public timeTriggerType()
        {
            this.randomDelayField = "PT0M";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT0M")]
        public string RandomDelay
        {
            get
            {
                return this.randomDelayField;
            }
            set
            {
                this.randomDelayField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class idleTriggerType : triggerBaseType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class registrationTriggerType : triggerBaseType
    {

        private string delayField;

        public registrationTriggerType()
        {
            this.delayField = "PT0M";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT0M")]
        public string Delay
        {
            get
            {
                return this.delayField;
            }
            set
            {
                this.delayField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class bootTriggerType : triggerBaseType
    {

        private string delayField;

        public bootTriggerType()
        {
            this.delayField = "PT0M";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        [System.ComponentModel.DefaultValueAttribute("PT0M")]
        public string Delay
        {
            get
            {
                return this.delayField;
            }
            set
            {
                this.delayField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/windows/2004/02/mit/task")]
    public partial class triggersType
    {

        private triggerBaseType[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BootTrigger", typeof(bootTriggerType))]
        [System.Xml.Serialization.XmlElementAttribute("CalendarTrigger", typeof(calendarTriggerType))]
        [System.Xml.Serialization.XmlElementAttribute("EventTrigger", typeof(eventTriggerType))]
        [System.Xml.Serialization.XmlElementAttribute("IdleTrigger", typeof(idleTriggerType))]
        [System.Xml.Serialization.XmlElementAttribute("LogonTrigger", typeof(logonTriggerType))]
        [System.Xml.Serialization.XmlElementAttribute("RegistrationTrigger", typeof(registrationTriggerType))]
        [System.Xml.Serialization.XmlElementAttribute("SessionStateChangeTrigger", typeof(sessionStateChangeTriggerType))]
        [System.Xml.Serialization.XmlElementAttribute("TimeTrigger", typeof(timeTriggerType))]
        public triggerBaseType[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
}
