//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Titanis.Asn1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Titanis.Asn1.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OID encoding ended with an incomplete identifier (high bit set)..
        /// </summary>
        internal static string Asn1_IncompleteOid {
            get {
                return ResourceManager.GetString("Asn1_IncompleteOid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ASN.1 integer read from the stream does not fit into the data type..
        /// </summary>
        internal static string Asn1_IntegerOverflow {
            get {
                return ResourceManager.GetString("Asn1_IntegerOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ASN.1 data did not contain a single char as expected..
        /// </summary>
        internal static string Asn1_InvalidCharData {
            get {
                return ResourceManager.GetString("Asn1_InvalidCharData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ASN.1 data is invalid..
        /// </summary>
        internal static string Asn1_InvalidData {
            get {
                return ResourceManager.GetString("Asn1_InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ASN.1 data did not contain a valid date/time.
        /// </summary>
        internal static string Asn1_InvalidDateTimeData {
            get {
                return ResourceManager.GetString("Asn1_InvalidDateTimeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ASN.1 field has an invalid string type..
        /// </summary>
        internal static string Asn1_InvalidStringType {
            get {
                return ResourceManager.GetString("Asn1_InvalidStringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member name &apos;{0}&apos; is not valid.  A member name must begin with a lowercase letter and contain only letters, numbers, and hyphens..
        /// </summary>
        internal static string Asn1_MemberNameInvalid {
            get {
                return ResourceManager.GetString("Asn1_MemberNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not have a publicly-accessible default constructor.  To be used with ASN.1 serialization, this is required..
        /// </summary>
        internal static string Asn1_MissingDefaultConstructor {
            get {
                return ResourceManager.GetString("Asn1_MissingDefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module name &apos;{0}&apos; is not valid.  A module name must begin with a capital letter and contain only letters, numbers, and hyphens..
        /// </summary>
        internal static string Asn1_ModuleNameInvalid1 {
            get {
                return ResourceManager.GetString("Asn1_ModuleNameInvalid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Asn1Type has already been attached to a module..
        /// </summary>
        internal static string Asn1_TypeAlreadyAttachedToModule {
            get {
                return ResourceManager.GetString("Asn1_TypeAlreadyAttachedToModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type name &apos;{0}&apos; is not valid.  A type name must begin with a capital letter and contain only letters, numbers, and hyphens..
        /// </summary>
        internal static string Asn1_TypeNameInvalid {
            get {
                return ResourceManager.GetString("Asn1_TypeNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ASN.1 reader expected tag 0x{0:X2} but encountered tag 0x{1:X2}..
        /// </summary>
        internal static string Asn1_UnexpectedTag {
            get {
                return ResourceManager.GetString("Asn1_UnexpectedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value name &apos;{0}&apos; is not valid.  A value name must begin with a lowercase letter and contain only letters, numbers, and hyphens..
        /// </summary>
        internal static string Asn1_ValueNameInvalid {
            get {
                return ResourceManager.GetString("Asn1_ValueNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bytes are not a properly encoded OID..
        /// </summary>
        internal static string Asn1DerDecoder_BadOidBytes {
            get {
                return ResourceManager.GetString("Asn1DerDecoder_BadOidBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contents are marked as constructed, but this is not permitted..
        /// </summary>
        internal static string Asn1DerDecoder_ConstructedNotPermitted {
            get {
                return ResourceManager.GetString("Asn1DerDecoder_ConstructedNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of a TLV overruns the length of the TLV containing it..
        /// </summary>
        internal static string Asn1DerDecoder_InnerLengthOverflow {
            get {
                return ResourceManager.GetString("Asn1DerDecoder_InnerLengthOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data contains an invalid decimal digit..
        /// </summary>
        internal static string Asn1DerDecoder_InvalidDecimalDigit {
            get {
                return ResourceManager.GetString("Asn1DerDecoder_InvalidDecimalDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Asn1DerDecoder_InvalidIndefiniteLength {
            get {
                return ResourceManager.GetString("Asn1DerDecoder_InvalidIndefiniteLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The underlying data is not a valid UTF-8 string..
        /// </summary>
        internal static string Asn1DerDecoder_InvalidUtf8Data {
            get {
                return ResourceManager.GetString("Asn1DerDecoder_InvalidUtf8Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the TLV exceeds what the implementation can handle..
        /// </summary>
        internal static string Asn1DerDecoder_LengthOverflow {
            get {
                return ResourceManager.GetString("Asn1DerDecoder_LengthOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NULL tuple is marked as constructed, which is not allowed..
        /// </summary>
        internal static string Asn1DerDecoder_NullConstructed {
            get {
                return ResourceManager.GetString("Asn1DerDecoder_NullConstructed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NULL tuple has value octets, which is not allowed..
        /// </summary>
        internal static string Asn1DerDecoder_NullHasValue {
            get {
                return ResourceManager.GetString("Asn1DerDecoder_NullHasValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DER encoder encountered an overflow while readinga tag.  The decoder only supports tags up to 32 bits in size..
        /// </summary>
        internal static string Asn1DerDecoder_TagOverflow {
            get {
                return ResourceManager.GetString("Asn1DerDecoder_TagOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encoded UTF-8 value is too large for the Char data type..
        /// </summary>
        internal static string Asn1DerDecoder_Utf8CharOverflow {
            get {
                return ResourceManager.GetString("Asn1DerDecoder_Utf8CharOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TLV is encoded with a primitive encoding and indefinite length, which is not allowed..
        /// </summary>
        internal static string AsnDerDecoder_IndefLengthPrimitive {
            get {
                return ResourceManager.GetString("AsnDerDecoder_IndefLengthPrimitive", resourceCulture);
            }
        }
    }
}
